### ISSUE TITLE
a new FIP: make sync faster by using the lotus daemon node in the same network which is fast or using trusted high quality node.

### ISSUE THREAD

**Issue by askender** [filecoin-project/FIPs#10]
This is a Technical FIP, or Filecoin Technical Proposal (FTP).
As talked in the thread: https://filecoinproject.slack.com/archives/C0179RNEMU4/p1600622389349900
many people are suffer from the lotus sync problem.

Background:
Two server running lotus daemon which use same network. One is vary fast in sync. the other one is always slow in sync.
We wish to speedup the slow one using the fast one by `add reward/score` to the trusted fast daemon manually.

Similar to:
```
INFO	pubsub	go-libp2p-pubsub@v0.3.6-0.20200910093904-f7f33e10cc18/gossipsub.go:1499	peer 16Uiu2HAmRH6MMzsPXNRWzQvFyQgV8CVe3e6hsffjNBm5FavWDhJJ 
didn’t follow up in 1 IWANT requests; adding penalty
```
expose the API of peer score will be better.

Fast sync will make the Filecoin network stronger.

**Comment by askender** [comment]
Related Technical FIP:    A light lotus daemon, which use less cpu and disk-space is useful in many case.

**Comment by whyrusleeping** [comment]
relevant: https://github.com/filecoin-project/lotus/issues/3532

**Comment by askender** [comment]
Thanks.   Move it to lotus issue as a feature requests,  and close the issue.
