### ISSUE TITLE
FIP proposal: alleviate window post penalty in a given time of period

### ISSUE THREAD

**Issue by ozhtdong** [filecoin-project/FIPs#103]
### Problem:
Chinese Vice Premier called for crackdown on cyrtocurrency mining in 5/24. As follow up instructions to IDCs might come up from the goverment realy soon, there could be risk that IDCs to cutoff infrastructure supplies for hosted filecoin nodes in China in a matter of days, this will be a massive hit on nodes hosted in China and will be a huge hit for filecoin network as well permanetnly. As an prepared emergency remediation for that worst case scenario, we propose an intermediate period for those nodes to migrate to oversea and their power can be allowed to come back afterward.

### Proposal:
Define a start height and end height, during start and end height, the ongoing missing window post pernality reduced to far less than 5br, and the 14 days deadline of terminate sectors for missing post suspended, while end height pass, penaltis and sector terminations resume. This will allow miners to have some time (presumerbily much longer than 14 days considering the logistic complexity) to migrate their nodes physically to the locations that mining is allowed for long term.

**Comment by CodingJzy** [comment]
Is this an announcement issued by the Chinese government? The financial committee only talked about prohibiting Bitcoin mining and trading, but did not talk about filecoin mining? I don't quite understand why it will have an impact on filecoin. fil mining is normal power consumption, right?

**Comment by CodingJzy** [comment]
Is this an announcement issued by the Chinese government? The financial committee only talked about prohibiting Bitcoin mining and trading, but did not talk about filecoin mining? I don't quite understand why it will have an impact on filecoin. fil mining is normal power consumption, right?

**Comment by ozhtdong** [comment]
There are quite a few different interpretations regarding that statement is cycling around in the last few days. Just thought it might be a good idea to do some preparation in case worst case scenario happens.

**Comment by CodingJzy** [comment]
I did not interpret the principle of fil mining in depth. I just read some articles saying that it is a post and copy proof. Without pow, it will not consume as much power and energy as Bitcoin. It should not be banned. Moreover, mining is relative to Bitcoin. Also has practical value,

**Comment by GaryGaoGJ** [comment]
It's very necessary for this proposal, the prohibition is not only  aim to power consumption, but also to prevent affect financial business by cryptocurrency.  The local government may not distinguish BTC mining and other cryptocurrency mining. So miners need to migrate Storage Power out of country, and need at least 2 month due to technical and supply chain factor.

**Comment by FHigher** [comment]
This is a good idea. It does not affect the persistence of stored data, and can reduce the loss

**Comment by kevinyankai** [comment]
I personally very much agree with this proposal. The government may not be able to distinguish between BTC mining and other cryptocurrency mining. Therefore, the government should give miners the time they need to move out of storage computing due to technical and supply chain factors.

**Comment by jennijuju** [comment]
> Since this type of event is always possible in any geographic location it would be better to have a more general solution that can be invoked whenever it is needed. What about a mechanism where a miner could stake some collateral to get a longer termination deadline?

I totally agree with this. I would also suggest that in the `product consideration` section of the FIP, we can add something like, "the network should accept this FIP under XYZ circumstance only"

**Comment by ozhtdong** [comment]
The original proposal can be easily implemented but is a quite rough one, because it doesn't consider different situations in different locations, local policy might be variant and whole network wide upgrade might be tough to coordinate. So this will only be used for last measure once the central government cleanly instruct to shutdown all mining facilities within few days or week across the country. The long term solution is to allow miners to decide when to pause and resume, meanwhile mining and commit sectors are prohibited from that miner, more collateral is required to extend termination is also quite reasonable. This can make miners to be more resilient not only while policy changes, but also other disasters like earthquake or super strong solar wind which might cut off infrastructure for days or weeks but data is preserved and can be come back online later.
This will require more crypto economic evaluation though and more change on protocol level I guess, so this might take more time to implement, before that, the original proposal is still can be used as safety net.

**Comment by steven004** [comment]
Basically, this is like to design a maintenance window for a miner, which could be longer than 1 month or  shorter than one day.  This will allow a miner pay much less cost in a particular period without requiring to submit wdPoSt when there is an early notice. 

This is more like the original idea of DeclareFaults mechanism, which is reasonable. However, after the FIP-0002 is implemented, the DeclearFaults method is rarely called, since it has no much use when one could miss one round of wdPoSt in most cases.  We may reconsider this, to have a better parameters or mechanisms for DeclareFaults by lowering the penalty as an option. This is reasonable, since an expected failure will have much less damage than an unexpected one.

**Comment by ozhtdong** [comment]
While both approaches can achieve same goal, but the implementation difference is pretty significant. One is change on miner actor level, another is on sector level. IMHO on miner level might require less change and much less run time cost on state tree migration.

**Comment by Stebalien** [comment]
Slightly related: https://github.com/filecoin-project/FIPs/issues/84. But that proposal is only suitable for very short periods of time.

**Comment by jennijuju** [comment]
FIPs are created here https://github.com/filecoin-project/FIPs/pull/106

**Comment by f8-ptrk** [comment]
is that fair to those who didn't have the possibility to declare such a maintenance window?
