### ISSUE TITLE
FIP Proposal: Client can make an off-chain deal and miner can use CC sectors to storage data without resealing 

### ISSUE THREAD

**Issue by andrewzhao87** [filecoin-project/FIPs#114]
### Simple Summary
Client can make an off-chain deal to miner. The miner will use existing or new CC sector to storage client's real data. If client want its off-chain data on chain, miner should upgrade the CC sectors to Regular Sectors with resealing.

### Problem

Right now, the total network power is more than 6EiB，but the real storage is just only 15PB（https://storage.filecoin.io/). There are a lot of CC sectors with the zero deal. The miner should have an easy way to use the existing CC sectors to store the real data from the clients, no more resealing. So that it can solve the problem about the idle hardware equipment.

The currently method is that the pledged sector can be replaced with a new sector containing deals.(https://docs.filecoin.io/mine/lotus/sector-pledging/#upgrading-pledged-sectors). However, it requires the deal to publish and new sector to seal. It will take up more resources of the miners and also occupy more resources of the network. Client storage costs will also increase because of it. 

### Proposed Solution
The client can choose whether to publish its own data and deal on chain or not.

- If the client make the on chain deal, the miner can store it in a new sector or upgrade the CC sector by 'mark-for-upgrade'.
- If the client make the off chain deal, there are not publishStorageDeals message, sealing and dealID etc. The client's data will be stored in the CC sector of the miner. At the same time, miners need to save DealCid and PieceCID. SectorPreCommitInfo also needs to be changed or add some data fields. (we also see some similar proposals at #57 #89)

Storing the off-chain data will save the gas fee, which is so expensive when the base fee is high especially. Like Verified data, the miners can provide the client another lower storage price than on-chain mode. The clients also can download files from the miner by the file CID.

If the client needs, it can change its off-chain deal on chain. The miner will migrate the data into the regular sector.

Especially, when the client finds that the miner do not provide services any more, it can create an arbitration or appeal. If the miner lost the data, the miner needs to pay the customer compensation for the loss of data. Meanwhile, the  power and pledge will also be slashed. (Perhaps we can discuss another FIP in detail)

**Comment by nicola** [comment]
Exciting, so great to read this idea!

(@lucanizzardo and I were about to post a proposal to try to solve the same problem).

**Comment by Wondertan** [comment]
Another cool side of the proposal - is that the described unsealed/off-chain data can be regular IPLD formatted data and thus retrievable from IPFS. This could be an additional solution for Filecoin/IPFS interoperability issue and even implement remote pinning API for miners. For a variety of cases, off-chain deals would give enough guarantees about data being stored. 

Also, it looks similar to optimistic rollup schema, but in this case, this can be called an 'optimistic storage deal'. That is, the deal is optimistically stored off-chain as IPLD data in the CC sector, which can be (1) upgraded to an on-chain deal and (2) disputed in the case it's not stored anymore(verification procedure?).

**Comment by anorth** [comment]
There are two different ideas in this proposal. 
- enabling off-chain deals
- upgrading CC sectors without resealing

FIP-0016 lists #57 as the venue for discussion about supporting off-chain deals. I think it best that this discussion be focussed around CC upgrades without resealing.
