### ISSUE TITLE
Adding a website version of the FIPs repo

### ISSUE THREAD

**Issue by bmann** [filecoin-project/FIPs#124]
I did a fair bit of work on the Ethereum EIPs repo and process and find that it's useful to have a website to link to.

I'm proposing to just use Jekyll, but of course publish and host it on IPFS. This means adding a few files for config and layout to this repo, but the fips folder just needs to contain markdown files like it does now.

Fission is happy to help with the publishing toolchain, I've setup a filecoin user that I can share the key for. This auto-builds on merge to master, and publishes to IPFS.

I suggest `fips.fil.org` get used as the DNS website version.

PR to master incoming.

**Comment by kaitlin-beegle** [comment]
Thanks for doing this, @bmann.  This is much needed. 

One of the things that the EIP is great about is clearly labeling where each improvement proposal falls within the development pipeline (e.g., adopted, in-process, last call, etc.).  Breaking out FIPs according to their status will help produce a level of cogency that the present repo lacks.  Organizing this is something I will work on in the coming weeks, and we can translate this structure to the website once it's set up. 

My only concern at the present moment is about page layout.  The colors are a bit difficult for me to read, and I wonder if others agree.  

Let's leave this open for a few days so folks can add comments, etc., but otherwise I see no issue with accepting the PR so that we at least have the current Jekyll version as a jumping-off point.

**Comment by bmann** [comment]
@kaitlin-beegle great, feel free to send people to my upstream repo at https://github.com/bmann/FIPs/tree/bmann-jekyll -- anything committed to that will auto-build to https://fips.fission.app/ and also update the PR.

It's a default design, no claims of being a designer here :) If you want to pick one of the more plain themes from this page, let me know, it's a one second change https://github.com/mmistakes/jekyll-theme-basically-basic -- I've moved it back to default, which is grey and white. The "sea" theme was to try and provoke someone to do something about the design :) This might be a good Gitcoin bounty project...

I can add status to the table. There really aren't that many FIPs yet so I wouldn't break them out into sections quite yet. DONE

Another request was reverse chronological sorting DONE

In general, I'd push for getting it live -- maybe only being blocked by an "official" subdomain -- and tweaking design from there. Because keeping this up to date as more FIPs get PR'd in is going to be painful.

NEW made a new `/fips/` page -- it just repeats what's on the home page, but could display something different.

NEW added spec section to individual FIP template. This needs cleaning up across all FIPs -- should probably be links or?

Updated site always auto-published here: https://fips.fission.app/

ALSO: rather than cluttering this repo with issues, I'm triaging in the repo for the PR as I work on stuff https://github.com/bmann/FIPs/issues/

**Comment by kaitlin-beegle** [comment]
@bmann looks awesome, I really like it.  Also, a contested choice, but I like b+w default layouts.  We can leave it for now...maybe, as the FIPs list grows, we can dedicate some in-house design team to it. 

Do you have any preferences for where we host the site link? I think the FIP repo 'About' section makes sense, but I'm open if you had other ideas :)

**Comment by bmann** [comment]
No preference on where to put it. A dedicated subdomain is the easiest to work with. Either fips.filecoin.io (makes sense, it's about the chain) or fips.fil.org (if this is going to be more about foundation related governance). Reflecting on Ethereum / Ethereum Foundation, the filecoin subdomain makes the most sense?

**Comment by momack2** [comment]
+1 to FIPs.Filecoin.io! maybe @andyschwab can help with setting up the subdomain? Excited to get this launched! Thank you @bmann!!

**Comment by andyschwab** [comment]
Quick update - we're staged to launch on fips.filecoin.io whenever the site is ready.

**Comment by kaitlin-beegle** [comment]
@andyschwab great! The first version of the website is currently hosted at [fips.fission.app ](https://fips.fission.app/).

Could you help us launch at the permanent URL?  Also, once the website is hosted by fips.filecoin.io, will we continue to make website updates via markdown files pushed to @bmann's Github repo?

**Comment by Kubuxu** [comment]
A nice feature for the website would be supporting Latex notation for mathematical formulas.
Unfortunately it would make reading FIPs on GH in the repo harder but would make some explanations much clearer.

**Comment by bmann** [comment]
Whoops, I'm behind on tracking this issue @andyschwab -- the PR I have setup is all working to auto build, needs to be merged to master here, I can probably get to that tonight.

In the meantime, `FIPs.Filecoin.io` --> you can use one of the custom domain methods to map this to the Fission IPNS name, eg. Cloudflare https://guide.fission.codes/developers/custom-domains/using-cloudflare-ipfs-gateway -- or message me in Filecoin Slack if you need help.

@Kubuxu -- need to figure out where best to file website requests without over-cluttering the repo here. Looks like we can add MathJAX support without too much trouble

**Comment by bmann** [comment]
@andyschwab you may still need a secret from me? Let me know if made it into the repo https://github.com/filecoin-project/FIPs/pull/147, or DM me on Filecoin slack if you have questions.

**Comment by bmann** [comment]
@andyschwab please let me know how I can help get this shipped with a domain.

**Comment by andyschwab** [comment]
We're deployed at: fips.filecoin.io!
