### ISSUE TITLE
FOP - New miner terminology proposal 

### ISSUE THREAD

**Issue by Stefaan-V** [filecoin-project/FIPs#127]
![unnamed](https://user-images.githubusercontent.com/83617805/127078910-c491e3b9-4c94-46f0-86e4-fd9e87b04faf.png)

## **Summary**

This proposal describes a change to rebrand the existing ‘miner’ references in marketing assets, documentation, communication channels and UX interfaces to a new definition called  'Storage Providers'. With this new proposal we are moving towards a naming convention that better represents our community partners that provide the storage infrastructure and services to the Filecoin network. This change will also help in highlighting the usefulness of the Filecoin network and is a start of a series of gradual changes we are proposing to help the network in creating a new narrative. We welcome feedback and input on the proposed changes below.

## **Change Motivation**

No blockchain is the same. Every single blockchain network comes with unique characteristics and incentive mechanisms that drive a prosperous community and implement a long-term sustaining strategy.

Filecoin's long-term vision has always been to create a decentralized, efficient and robust foundation for humanity’s most valuable data. To support this vision, we are relying on a wide network of community members that provide and commit storage to the Filecoin network, currently referred to as the Filecoin miners.

With Filecoin’s rapid storage growth and adoption of web3 applications, the community and the extended ecosystem members are requesting a branding change in how to position the miners.

### **The main reasons are:**

1. **To connect better with the end-user market.**  Enterprises and other Web2 members looking to store data on the Filecoin network are typically not familiar with the crypto concepts that underpin the tokenomics. Hence, the concept of a miner and or mining activities can lead to confusion with non-crypto-savvy users and distract from the real value that the network provides. Clients are used to hearing terminologies like cloud providers, service providers, etc.
2. **To communicate the usefulness of the network**. Different blockchains have different usages. Some customers and Web2 members wrongly assume that ‘mining’ refers to a process that is delivering no useful output, is highly energy consuming and is not contributing in producing unique capabilities. Filecoin is different from other blockchains as it delivers a decentralized network that stores useful data in an efficient way and it drives incremental value thanks to its unique capabilities (e.g. immutability). It is important to communicate and market those useful attributes through straightforward terminology that is easily recognized by the Web2 and Web3 members.
3. **To take a leadership position.** Filecoin miners not only contribute to providing archive storage for existing Web2 datasets, but also form the native storage foundation for the Web3 world of decentralized applications. It is important to highlight the differences between the traditional Web2 cloud providers and those storage providers that are able to deliver a unique experience or better service through Filecoin's decentralized capabilities. As we move our branding forward, our providers can position themselves as the infrastructure and service providers of storage and retrieval of NFTs, Web3 data sets, Web2 archives and many more.

### Input & Feedback

This proposal includes input gathered from feedback sessions with miners in the storage provider working groups and ecosystem partners.

The goal was to rename a subset of the current miner related terminologies and replace them with a proposal that better describes the current activities and the value creation to the network. The initial feedback we received from the community has been in favor of this new change.

## The New Terminology Mapping

The following table highlights in more detail the terminology mapping.

**The New Terminology Mapping**
|Current Terminology|New Proposal |Abbreviated Version |
|---|---|---|
| Miner  | Storage Provider (SP)  | Storage Provider   |
| Storage Miner  | Storage Provider (SP)  | Storage Provider |
| Retrieval Miner | Retrieval Provider (RP)   | Retrieval Provider |
| Pool Name | Storage Provider Name | Provider Name |
| Miner Rig  | Storage System |Storage System |
| Miner Pool  | Storage Pool | Storage Pool |
| Mining/Block Rewards | Block Rewards  | Rewards |
|  Deal Payment | Deal Income   | Income  |
|  Miner ID **(third party UX) | Storage Provider ID   | Storage Provider ID |
| Miner Working Group| Storage Provider WG| Storage Provider Working Group|

**Once the community reaches consensus, we ask all participants in the Filecoin ecosystem to update any miner_ID references to Storage Provider_ID in the UX interfaces.

The following table highlights in more detail the description of these new terms.

|  Proposal | Description  |
|---|---|
|  Filecoin |  A decentralized storage network existing of a multi-verse ecosystem where storage providers deliver the storage infrastructure supply. |
|  Storage Providers (SP) |  A  Filecoin Storage Provider exists of 1 or multiple storage systems.  |
|  Block Rewards |  The rewards gained from committing storage capacity and storing useful data.  |
|  Deal income |   Income received for storing useful data through deal making. |
|  Storage System |   A Storage system can exist of 1 node or a cluster of nodes responsible for sealing,  storing and retrieving data. A storage system has one ID |
|  Storage ProviderID |  We ask all network browsers and other ecosystem partners to represent the miner_IDs as storage provider_IDs in the UX. |
|   Retrieval Providers|   A provider who provides retrieval services. |
|  Storage Provider Name | A Storage Provider is typically represented by a custom tag in a network explorer UX and can exists of 1 or multiple storage systems. This purely added as guidance for third-party explorers.  |
| Storage Pool |  A combination of multiple storage systems that are pooled together as 1 single entity.  |
| Storage Provider WG | The working group of world wide storage providers that focuses on the storage provider ecosystem.|

## What content assets will be updated?

With the support of the community, we will start using the new terminology in newly created marketing assets. In the next couple of weeks and months we also suggest to update the following websites and assets and promote the new terminology where possible.

**List of existing assets/websites we propose to update over time**

- [filecoin.io](https://filecoin.io/), [docs.filecoin.io](https://docs.filecoin.io/)
- github /filecoin-project
- Filecoin Foundation website
- Partner Block trackers
- and other ecosystem tools

We ask the Filecoin community to adopt and help communicate these new changes to the market. Once we reached consensus, we also ask the community to update the community tools and marketing assets to include these new naming proposals.

## The journey ahead

We understand  this change doesn't happen in a day and it will be a multi-phased approach of content iterations and messaging adjustments across the whole ecosystem. This is the first phase of this journey that will take the full community to participate.

The Filecoin long-term strategy is to continue to educate the mainstream market and create awareness on the benefits of the network and how a distributed and decentralized architecture differentiates from the centralized solutions of the Web2 world.

**Comment by NSC-FIL** [comment]
Well written. +1 on the new branding.

**Comment by timguo-ipfs** [comment]
Great proposal, just one concern about:
<!DOCTYPE html>

Miner Rig | Storage System | Storage System
-- | -- | --

The storage system may not reflect the machines or equipments behind it. 
Can we use **Storage Server** instead?

**Comment by Stefaan-V** [comment]
We thought about that, but considering a Filecoin architecture can exist of
1 or multiple compute and storage servers, the feedback was that the word
"system" would be more encompassing of all the configurations. A Storage
server would only call out a single server.

**Comment by ribasushi** [comment]
`Block Rewards` makes me rather queasy: it is too close to BTC&Friends. We should strive to move away from that space. Some off the cuff suggestions, given how what this part of the network does is securing itself:

- Security Rewards
- Security Income
- Consensus Rewards

**Comment by kemihu** [comment]
This is a fantastic proposal -- kudos to @Stefaan-V -- PiKNiK has been using these terminologies unofficially for several months. In our experience, the broader tech market is far more receptive to this neutral language.

**Suggestion**: Change Filecoin --> "FIL Network"
**Reason**: _coin_ has a charged connotation 
**Analogy**: what was formerly _American Telephone and Telegraph_  is now just "AT&T" to get away from the irrelevance of telegraphs

**Comment by jennijuju** [comment]
> This is a fantastic proposal -- kudos to @Stefaan-V -- PiKNiK has been using these terminologies unofficially for several months. In our experience, the broader tech market is far more receptive to this neutral language.
> 
> **Suggestion**: Change Filecoin --> "FIL Network"
> **Reason**: _coin_ has a charged connotation
> **Analogy**: what was formerly _American Telephone and Telegraph_ is now just "AT&T" to get away from the irrelevance of telegraphs

👍🏻 Please create another FIP  as this term is not directly miner operation related.

**Comment by Meatball13** [comment]
Yeah, great ideas here and think it would help the network to rebrand anything related to Mining to Storage Provider, etc.  I think it would level set both clients and potential Storage Providers that FIL just isn't some crypto currency get rich scheme but a true infrastructure of distributed storage supplied by professional technologists.  Leaving references to 'mining' definitely implies the wrong connotation for where the network wants to sit.

**Comment by alexzhenyu** [comment]
<html>
<body>
<!DOCTYPE html><figure class="md-table-fig" cid="n0" mdtype="table" style="box-sizing: border-box; margin: 1.2em 0px; overflow-x: auto; max-width: calc(100% + 16px); padding: 0px; cursor: default; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">

提案 | 描述
-- | --
Filecoin | 一个多元生态的去中心化存储网络, 存储服务商可以在这里提供存储基础设施和相关服务。
存储服务商 | 基于一套或多套存储系统的存储服务商。
出块奖励 | 通过提供存储容量和存储有效数据获得的奖励。
订单收入 | 通过处理订单并存储有效数据获得的收入。
存储系统 | 存在于一个节点或者多个节点组成的集群的存储系统，这些节点负责密封、存储、和检索数据。一个存储系统有一个ID。
存储供应商ID | 我们请求所有存储网络浏览器和其他生态的伙伴们在用户界面中用存储服务商ID表示miner ID。
检索服务商 | 检索服务的提供者
存储服务商名称 | 存储提供者一般以一个特定的标签在存储网络浏览器的用户界面中展示其名称，而且可以存在于一套或多套存储系统中。这个标签仅在第三方存储网络浏览器中起识别作用。
存储资源池 | 多个存储系统组成的一个实体。
存储服务商工作组 | 全球范围内的专注于存储生态发展的存储提供者组成的工作组。

</figure><br class="Apple-interchange-newline">
</body>
</html>
This is a Chinese version of the new terminology created by StorSwift team. It's for reference only.

**Comment by Stefaan-V** [comment]
> `Block Rewards` makes me rather queasy: it is too close to BTC&Friends. We should strive to move away from that space. Some off the cuff suggestions, given how what this part of the network does is securing itself:
> 
> * Security Rewards
> * Security Income
> * Consensus Rewards

Any other opinions out there on this topic?

**Comment by jimpick** [comment]
I'm planning to rebrand https://miner.report/ to https://provider.quest/ (it will take some time, there are a lot of references to rename)

I strongly agree with this. "Crypto Mining" is entering the popular lexicon via the news cycle and is becoming closely associated with Bitcoin and wasteful environmental practices as well as a lot of scam behaviour. It will be easier to portray Filecoin as one of the "good guys" if different language is adopted.

**Comment by kaitlin-beegle** [comment]
Closing due the passage of FIP-0018
