### ISSUE TITLE
Liquidity Improvement for Storage Miners

### ISSUE THREAD

**Issue by zixuanzh** [filecoin-project/FIPs#14]
## FIP-000X Liquidity Improvement for Storage Miners

Read: [FIP Draft](https://github.com/filecoin-project/FIPs/pull/15)

## Abstract

This proposal allows a substantial fraction of block rewards to be immediately available for withdrawal to allow for greater liquidity and decision freedom for storage miners. The majority of mining rewards continue to vest over 180 days as collateral to reduce initial pledge, to align long-term incentives, and to guarantee storage reliability.

**Comment by dayou5168** [comment]
Great. bro.
we want survive .

**Comment by apdan510** [comment]
Yes thank you. All we want is to reinvest the fil back into more sectors

**Comment by weforu** [comment]
good idea

**Comment by benjaminh83** [comment]
Makes total sense. Otherwise we could see a drop in sealing new sectors, as miners will slow down sealing to match the limited FIL supply from vesting block rewards with needed collateral for new sectors. That not an ideal/wanted behavior.

**Comment by hyunmoon** [comment]
Would it be possible to allow the rest to be used as pledge collateral?
25% is better than 0% but I'm afraid it's still not enough to keep our machines running.
We need liquidity for pledge collateral more than for withdrawal.

**Comment by tancs2020** [comment]
Actually 25% is still far from enough. The FILs that the investors can sell is  more than  10 times as miners very day. IT IS UNFAIR !

**Comment by yskj-liang** [comment]
We need more fils as collateral, or lower mortgage standards

**Comment by tuzi14135** [comment]
We need to lower the mortgage standards

**Comment by backeyzhang** [comment]
The 25% release is still not enough, the locked position should be used as collateral according to the previous statement

**Comment by asdisg** [comment]
Now it’s no longer extravagant to ask for fairness, but whether you have calculated. If the increase in computing power released by miners is far from being mortgaged, even if it is all released, it will not be enough for mortgage, let alone only 25%, and your previous promise, lock The warehouse can be mortgaged, this matter is still not realized near the main network

**Comment by waynewyang** [comment]
@zixuanzh @jbenet 
Compared to the previous economic model, it's a good news  for miners that 25% of the reward is released immediately.

However, miners need available  balance to increase power, but according to the current economic model, the rewards released are still not enough to maintain the normal growth of miners' power. If the available amount of reward cannot be used for the growth of power, the existing Filecoin hardware resources will possibly flow to other areas, causing the loss of resources in the Filecoin ecosystem.

For the entire filecoin ecosystem, it may be better to increase the proportion of rewards released immediately or shorten the reward release cycle, For example t01248, if the immediate release ratio change to  50%(Or immediate release ratio  is 25% , and change the reward release period to 90 days), then It can basically meet the growth of miner's power.

As long as the miner's reward can meet the growth of its power, it can ensure that the Filecoin ecological hardware resources will not be lost.
Thank you.

**Comment by cwhiggins** [comment]
I do not agree with the rational that block reward should match miner growth potential, that is ridiculous.
 Exponential growth is not sustainable in any system, the network has been growing too fast as it is.  If PL expects growth to continue at the same rate then they should be telling all participants of smaller size to bow out, now.

**Comment by waynewyang** [comment]
@cwhiggins For large miners and small miners, this is the same logic.The increase of miners' computing power (which will be real transactions in the future) belongs to the production market, and the idleness of the production market is not beneficial to the ecology.
Miners should have the basic right to participate in the production market or financial market.
This is better for both big miners and small miners.

**Comment by NSC-FIL** [comment]
Any change to release pledged collateral should not incentivize miners to liquidate their FIL to simply sell for profit in the financial market.  How to keep the released FIL in the production market is important for the stability of the Filecoin network IMHO.  I agree some pledged collateral should be released for miners to continue operations and calculations should be made to limit the amount so not to give too much advantage to the top miners who already have a huge advantage in power growth. Smaller and newer miners should have a chance to sustain and grow to keep Filecoin decentralized.

**Comment by caokun8341** [comment]
Personally, I feel that an unlimited pile of hard drives and sealing a bunch of useless garbage data is a great waste. Only by storing the user's valid data is it meaningful to get rewards!

**Comment by hgatys** [comment]
I think somebody don’t know the essence of this problem is the contradiction between miners and early investors & protocol lab team.
You have to calculate that more than 90% of the circulating FIL is not on the miners, this is the true sadness of the people.
This is not a discussion of large miners and small miners.It is the problem that all miners have too few FIL in circulation.

**Comment by hgatys** [comment]
> Actually 25% is still far from enough. The FILs that the investors can sell is more than 10 times as miners very day. IT IS UNFAIR !

Agree. the FIL holder complete control of the financial trading market, this is the point.

**Comment by waygo07** [comment]
I have become accustomed and tired of this practice of PL. The FIL in circulation is not enough. It is in the hands of PL and investors. Small miners can no longer play. Please increase the ratio to 90%, not 25%. Not enough, not enough!

**Comment by hgatys** [comment]
> I think somebody don’t know the essence of this problem is the contradiction between miners and early investors & protocol lab team.
> You have to calculate that more than 90% of the circulating FIL is not on the miners, this is the true sadness of the people.
> This is not a discussion of large miners and small miners.It is the problem that all miners have too few FIL in circulation.

waygo07兄弟有理, 楼上很多人,根本就不知道这个问题是讨论啥,还在区分大矿工、小矿工,可笑至极.
这么简单的道理不能明白, 看看我上面说的,被割了还帮忙数钱.

**Comment by waygo07** [comment]
haha,I hate large miners, but now I sympathize with large miners.

**Comment by talktone** [comment]
I would suggest block rewards should be 100% vested for sector collateral (only). That would be a huge incentive for miners to continue adding more sectors. 180-day vesting period should still be applied for withdrawing block rewards to ensure the stability and security of the network.

**Comment by LeFiX1** [comment]
We need to live and work. good Idea

**Comment by bonoyang** [comment]
Great. bro. This proposal is a good way to survive.

**Comment by momack2** [comment]
From what the community has said above and in Filecoin slack discussion channels, there is a **lot** of support for this proposal.🚀  This proposal walks the line between giving miners much-needed resources to continue sealing new capacity and proving existing capacity, while not creating pressures/incentives for large miners to liquidate all their collateral or DOS the network growth to exclude small/new miners. Cryptoecon simulations reinforce this parameter choice as a good balance between short-term flexibility and long-term alignment with network success.

I also hear a lot of "yes, and" -- Yes, make this change, and **also** [make some locked rewards available for pledge collateral | increase the ratio unlocked up-front from 25% to XX% | increase the ratio unlocked for miners with good deal success rates to incentivize useful storage | etc]. These are all ideas we can explore as a community, but that require deeper analysis into the incentives they'd create in the long-term success of the network. This proposal is very simple to implement and ship ASAP, and we don't want to block an improvement the community clearly has strong agreement for behind harder/longer analyses. For these additional modifications and proposals, please open a new FIP to ensure we can analyze as a community how it would benefit the long-term utility and success of the Filecoin network. 🙏

This week, the 4 Filecoin implementations (lotus, forest, fuhon, and go-filecoin) reviewed this proposal and have approved it for implementation and inclusion in the next upcoming state upgrade. 🎉  Please look out for more details on timing for that upcoming state upgrade in #_fil-announcements. For now, I'm going to mark the FIP as `Accepted`.

**Comment by flyworker** [comment]
25% is OK for me

**Comment by hedoturkoglu** [comment]
> From what the community has said above and in Filecoin slack discussion channels, there is a **lot** of support for this proposal.🚀 This proposal walks the line between giving miners much-needed resources to continue sealing new capacity and proving existing capacity, while not creating pressures/incentives for large miners to liquidate all their collateral or DOS the network growth to exclude small/new miners. Cryptoecon simulations reinforce this parameter choice as a good balance between short-term flexibility and long-term alignment with network success.
> 
> I also hear a lot of "yes, and" -- Yes, make this change, and **also** [make some locked rewards available for pledge collateral | increase the ratio unlocked up-front from 25% to XX% | increase the ratio unlocked for miners with good deal success rates to incentivize useful storage | etc]. These are all ideas we can explore as a community, but that require deeper analysis into the incentives they'd create in the long-term success of the network. This proposal is very simple to implement and ship ASAP, and we don't want to block an improvement the community clearly has strong agreement for behind harder/longer analyses. For these additional modifications and proposals, please open a new FIP to ensure we can analyze as a community how it would benefit the long-term utility and success of the Filecoin network. 🙏
> 
> This week, the 4 Filecoin implementations (lotus, forest, fuhon, and go-filecoin) reviewed this proposal and have approved it for implementation and inclusion in the next upcoming state upgrade. 🎉 Please look out for more details on timing for that upcoming state upgrade in #_fil-announcements. For now, I'm going to mark the FIP as `Accepted`.

How was it getting approved? Is there a proposal approval procedure? So you just tell us there's a proposal, and after a couple of days you tell me again there were more people voted yes than no so it's approved? After manipulating the crypto market, you start to manipulating communities' voices?

**Comment by ncgege** [comment]
As far as the FIL price is concerned, it is not suitable to do this ant this time. may be 6 months or one year later.

**Comment by Steve-IPFSUNION** [comment]
The 25%/75% plan in the proposal 0004 is less than enough in practice. Instead of focusing on the front-collateral-ratio, I would like to propose a new back-collateral model as following:
 
No front-collateral is required to lower entry threshold. Collateral token will be automatically pledged from the block prize until it reach a certain amount. (i.e. 0.2-0.3 FIL/T at current ratio). 
 
There are 3 major advantages in back-collateral business model:
 
1.     From the technology side, lower entry threshold means more players can join the Filecoin mainnet which will broadly increase the number of mining machines and developers. A stronger infrastructure means more competitiveness and abilities for the future business applications in real life.
 
2.     From the community side, lower entry threshold will definitely increase the number of participants who are involved in Filecoin community in various ways. These participants might help the Filecoin in different ways such as: buying mining machine, propagandize Filecoin via different media channel, formulating local Filecoin communities, trading FIL in the exchange or OTC etc. All these things will increase the Filecoin’s influence in both crypto market and the real business world. With all these community members and their positive consensus and faith, the liquidity and market price will also be improved.
 
3.     The pledge ratio per T need no dramatically changed therefore the “safety concern” can be eased. The only problem for miner is that they may not be able to make withdraw before their mining machines are fully pledged. But it is still much better than pay much more to buy extra FIL to pledge before mining and exposed in unexpected market risk. Moreover, this “back-collateral model” will also delay the miners’ withdraw, so that less token will be released to the secondary market and might help with the market price as well.
 
Please consider this proposal seriously. As one the community member, we really want to help with Protocol Labs to perfect the Filecoi

**Comment by jbenet** [comment]
@Steve-IPFSUNION those are good ideas, you should write up the proposal more concretely, so people can evaluate it (have concrete parameters, so we and others can model & simulate)

**Comment by momack2** [comment]
This has been implemented and shipped, so closing this issue and I encourage others to make new FIPs for additional proposals!
