### ISSUE TITLE
FIP Discussion: Snap Deals

### ISSUE THREAD

**Issue by Kubuxu** [filecoin-project/FIPs#145]
Discussion issue for FIP-XXXX
Replaces FIP-0017 (#131)

### Motivation
Unlocking currently available CC sectors (8EiB) for deals by allowing CC to be updated to contain deals in a lightweight and fast process.

### Differences from FIP-0017

- Update is now one message process with no waiting for randomness involved. Time to complete the upgrade reduced from 3h to **less than 30min.**
- Encoding function changed slightly with a minimal compute cost increase (computing 512 Posseidon hashes).
- Proof creation cost is slightly increased (10%) to enable cheap verification.
- Proof verification cost is radically reduced by performing challenge generation in the circuit.

FIP draft to follow soon

**Comment by stuberman** [comment]
I am wondering about security considerations. Without resealing a sector, doesn't this violate the integrity of a sector? More to the point, does this open the door to modifying content of a sector without the security provided by the original proof?

**Comment by ZenGround0** [comment]
It does not.  If you can find a way to do this you have found a currently unknown attack on the snap deals upgrade construction that would require a security modification for the FIP to make it to mainnet.

I'm not an expert here but the general property of sectors providing the system security is that sectors are not cheap to compress.  The snap deals upgrade mechanism is carefully designed to maintain this incompressibility property.  Conceptually the reason we expect this to be possible at all is that the upgrade starts with an incompressible sector and maintains an acceptable level of incompressibility while combining user data with the sector.

**Comment by kaitlin-beegle** [comment]
**FYI** - Snap Deals were discussed in various Storage Provider meetings today and several concerns were raised.  These include general questions about security, as well as specific concerns about snap deals disproportionately incentivizing CC sector creation.  

The various storage provider working groups, etc., would like to weigh in on whether or not the upgrade is configured to support sending 1 or 2 messages.  However, more information is needed.  I'll be working to gather additional information from various stakeholders over the course of the next week and sharing it across various Slack channels. 

@Kubuxu do you have a timeline for when you expect to submit a PR for the FIP draft?

**Comment by kaitlin-beegle** [comment]
This FIP officially moved to 'accepted' status on 1/24! Closing issue!
