### ISSUE TITLE
staking

### ISSUE THREAD

**Issue by CodingJzy** [filecoin-project/FIPs#157]
Like Polkadot, near, and sol are similar pos. Although the consensus of fil is not proof of staking, don't you think that the threshold of fil mining is a bit high? Ordinary users can't participate at all, even if they have 10,000 fil in their hands, they can't enjoy coins. I have an idea. Miners now also have pre-stakes in them. Can this part be part of ordinary users? Similar to the nominee in Polkadot, the coins are handed over to the real miners, and then restricted by some punishment mechanism or other rules, ensuring and binding the safety and benefits of both, and then both benefit at the same time. In this way, ordinary users also Being able to participate also allows fil itself to provide liquidity, and its development is also more long-term. The goal of relying solely on fil's future storage services and query services to provide liquidity is too long and requires a huge ecosystem. In addition, there are too many centralized miners in the market, mixed with fish and dragons, with a lot of commissions, and the intensity of centralization is high. Ordinary consumers cannot fully trust them; the other is defi, which allows ordinary Users can also participate in staking and liquidity mining, but at present, there is no better one, the income is very low, and they are afraid of insecurity.

**Comment by whyrusleeping** [comment]
I'm not sure where youre getting 'a high degree of centralization' from, if you take a look at the miner graph, the biggest miners have low single digit percentages of the total power: https://filfox.info/en/stats/miner

As for your proposal of wanting something to do with your FIL, We are thinking through lending contracts that would let users (or coalitions of users) fund the collateral of miners in exchange for some return. Is that roughly inline with what youre wanting?

**Comment by kaitlin-beegle** [comment]
Hi @CodingJzy, this proposal sounds familiar.  Are you by chance working with @catthehunter? 

For more info, see the [Filecoin Financing Plan Grant proposal](https://github.com/catthehunter/devgrants/blob/aeb5c048dd5cb78412bc1ec8d2a6c7f89e4e2d95/open-grant-proposals/Filecoin%20Financing%20Plan.md)

**Comment by CodingJzy** [comment]
Hi, @kaitlin-beegle , if the world has the same ideas as me, I will feel very happy. However, I don’t know what you said @catthehunter. We are not working together either. I am Chinese, just an ordinary programmer, I don't have a team, and I don't want to participate in any financing!

**Comment by CodingJzy** [comment]
> 嗨@CodingJzy，这个提议听起来很熟悉。您是否偶然与@catthehunter 合作？
> 
> 有关更多信息，请参阅[Filecoin 融资计划拨款提案](https://github.com/catthehunter/devgrants/blob/aeb5c048dd5cb78412bc1ec8d2a6c7f89e4e2d95/open-grant-proposals/Filecoin%20Financing%20Plan.md)

Hi, @kaitlin-beegle , if the world has the same ideas as me, I will feel very happy. However, I don’t know what you said @catthehunter. We are not working together either. I am Chinese, just an ordinary programmer, I don't have a team, and I don't want to participate in any financing!

**Comment by CodingJzy** [comment]
> 我不确定你从哪里获得“高度集中化”，如果你看一下矿工图，最大的矿工在总算力中所占的百分比很低：[https](https://filfox.info/en/stats/miner) : [//filfox.info/en/统计数据/矿工](https://filfox.info/en/stats/miner)
> 
> 至于你想要与你的 FIL 做点什么的提议，我们正在考虑借贷合同，让用户（或用户联盟）为矿工的抵押品提供资金以换取一些回报。这与您想要的大致相符吗？


> lending contracts

**Comment by CodingJzy** [comment]
> I'm not sure where youre getting 'a high degree of centralization' from, if you take a look at the miner graph, the biggest miners have low single digit percentages of the total power: https://filfox.info/en/stats/miner
>

**Comment by CodingJzy** [comment]
> Hi @CodingJzy, this proposal sounds familiar. Are you by chance working with @catthehunter?
> 
> For more info, see the [Filecoin Financing Plan Grant proposal](https://github.com/catthehunter/devgrants/blob/aeb5c048dd5cb78412bc1ec8d2a6c7f89e4e2d95/open-grant-proposals/Filecoin%20Financing%20Plan.md)

Hi, @kaitlin-beegle , if the world has the same ideas as me, I will feel very happy. However, I don’t know what you said @catthehunter. We are not working together either. I am Chinese, just an ordinary programmer, I don't have a team, and I don't want to participate in any financing!

**Comment by CodingJzy** [comment]
> I'm not sure where youre getting 'a high degree of centralization' from, if you take a look at the miner graph, the biggest miners have low single digit percentages of the total power: https://filfox.info/en/stats/miner
> 
> As for your proposal of wanting something to do with your FIL, We are thinking through lending contracts that would let users (or coalitions of users) fund the collateral of miners in exchange for some return. Is that roughly inline with what youre wanting?

Yes, you're right. From the perspective of storage service providers, there is no centralization and high concentration, the computing power is also scattered, and the block reward is also fair. However, that's not what I mean. What I want to express is that as an ordinary person and fil lover, I can't participate in mining. Unlike Polkadot's dpos, ordinary users can nominate their Polkadot coins to multiple authenticators, and both benefit at the same time. It's like I opened a casino. Only the rich can gamble here, and the poor can't come in. In addition, fil miners themselves also need to pledge some fil coins. Whether some of them can be let out by ordinary users, they can charge some commissions and issue some income maintained at an annualized rate of about 10%. At present, in China, ordinary users can only give the money to the centralized miners, who will collect the draw. There are some fraudulent companies, and the company also has the risk of running away. Let ordinary users mistakenly think that filcoin project is a pyramid scheme and a Ponzi scheme.

For the lending contracts you mentioned, there are also related defll DAPP. I have known defil, Fido and dmex. And so on, but they are not authoritative enough, the transaction fee is also high, and the income is not obvious.

**Comment by kaitlin-beegle** [comment]
Hi @CodingJzy, thanks for providing further explanation! I appreciate you bringing this to attention. 

I will bring this up in one of next week's storage provider working groups and will report back with any ideas that the group has.

**Comment by CodingJzy** [comment]
> Hi @CodingJzy, thanks for providing further explanation! I appreciate you bringing this to attention.
> 
> I will bring this up in one of next week's storage provider working groups and will report back with any ideas that the group has.

Ok, thank you, no matter what the result is, I am looking forward to it. :smile:

**Comment by CodingJzy** [comment]
> Hey there, @CodingJzy! I brought this topic up with the North American Storage Providers working group and they agreed that you raise a great point. Upfront and other investment costs for storage providers are quite high, and these costs seem to scale with the size of storage provided to the network.
> 
> It seems like there are various ways of addressing this issue, but no clear path quite yet. Unless you have a specific way that you would like to see this issue solved, what do you say about having me move this issue to our new (not yet open!) FIPs discussion forum?
> 
> That way, we can continue to gather feedback and ideas on this topic without it getting lost in the shuffle of FIP drafts. Does that work for you?

Hi, @kaitlin-beegle ,I am very happy to see your reply. In fact, I just want to make a small comment, and I don’t want to make any FIP, because it is too complicated for me. Even though I refer to the template, I can’t write anything. 

All in all, if you can discuss it, you can discuss it, and if you can change it, you can change it. I look forward to seeing similar FIP changes in the future. If not, it doesn't matter. The rest is left to you. Ha ha!

---
fip:

title: Reduce the cost of storage providers

author: @CodingJzy

status: WIP

type: Technical

category: networking

created: 2021-09-28

spec-sections:

- section-systems.filecoin_mining
- section-algorithms.cryptoecon.design-principles-justification

---

## Simple Summary

The investment cost of storage providers is getting higher and higher, and ordinary users have no better and safer ways to participate.

## Abstract

As an ordinary person, I am looking forward to the future of the file project. My wallet has 10,000 fils, but for now, I have no safe way to increase these 100 million fils.

## Motivation

Currently, storage providers mainly include the following types:

- personal：go to the secondary market to buy fil coins or use the dug coins to continue to pledge
- company：Not only that, many companies sell their own computing power services, ordinary people buy fil coins, and then use the coins to buy their computing power, or go to them for joint mining.

No matter who it is, their investment costs are high. And for ordinary people, there are also great security risks: the company's random pricing and charging; the company's system withdrawal fees and quotas are different; the company can tamper with data; the company has the risk of running away. After all, this company is a centralized organization there.

So why not decentralize this intermediate step? Allow ordinary users to participate in mining without going through a miner. Of course, this mining does not mean providing storage, just providing pledges. This adds another role to the participants in the Filecoin economy.

## Specification

## Rationale

Storage providers also don't need to pledge their own coins. The new role transfers their idle coins to the storage provider in a safe way. After the block reward is generated, the storage provider divides a portion into the new role. Of course, the miners who actually provide storage services should account for most of the reward, and the new role is only a small part. Normally, it can be about 10%, which is better than putting the wallet directly without appreciation.

## Backwards Compatibility

## Test Cases

## Security Considerations

## Incentive Considerations

In this way, more ordinary people are willing to contribute their coins, which not only increases their investment income, but also reduces the cost of storage providers.

## Product Considerations

1. The storage provider’s initial pledge days were 540 days, which seems to be a long time. If a new character participates, will it take that long to unlock? After all, the rest of the pos public blockchains are pledged at any time, and the pledge is released at any time.
2. If the initial pledge currency is provided to the storage service provider through a new role, will it increase the storage service provider’s chance of doing evil and reduce their cost of doing evil?
3. Does it affect the investment income of institutions that actually provide storage services? Will they be willing to do so?
4. If you want to add new roles to participate in economic construction, you need to design a good rule to restrict each other and benefit from mutual cooperation, which will promote the circulation of fil coins and the development of fil projects.

## Implementation

## Copyright Waiver

Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by anorth** [comment]
On-chain financial protocols will be much, much easier after the FVM enables contract innovation and iteration without consensus protocol upgrades. I would propose that we shelve this for now in order to focus on enabling that fundamental capability. And then once we have, anyone could implement protocols like this so we won't need the FIP process for it. We *may* need a protocol change to expose some little primitive information or behaviour to those contracts, but it's too soon to tell what that might be.

**Comment by catthehunter** [comment]
Hey @CodingJzy  this is Catthehunter also from China, this is my proposal (https://github.com/filecoin-project/devgrants/pull/291). Maybe you have some idea about it? We can talk about it!

**Comment by kaitlin-beegle** [comment]
Closing this issue! This topic is being addressed in multiple different ways, and the introduction of the FVM will largely make this type of cost pooling an implementation feature rather than a protocol enhancement.
