### ISSUE TITLE
Filecoin Plus project terminology explanation proposal

### ISSUE THREAD

**Issue by swatchliu** [filecoin-project/FIPs#159]
​                 ![img](https://docimg6.docs.qq.com/image/8nJUsvcvZPXfOlmL9UmeUw.png?w=2835&h=1595)        

**\#Summary**
Bytebase proposes the definition of a new term. ByteBase Privacy Storage Platform provides easy-to-use SaaS services and OpenAPI services for Chinese enterprises. We connect both Data Providers and Storage Providers. Data Providers enjoy stable and reliable decentralized storage services based on Filecoin networks and Storage Providers enjoy the benefits from data storage and retrieval. Meanwhile, as a Notary ByteBase proposed a new definition for the Filecoin Plus project in the Filecoin community. This change will help the Filecoin network to attract more people to use it for storage and transactions. We welcome feedback and comments on the proposed changes below.

**\#Change Motivation**
Filecoin Plus is based on a set of guiding principles, detailed in FIP-0003, that focus the program on increasing Filecoin's effectiveness at becoming the decentralized storage network for humanity's most important information.

Root key-holders, notaries, clients, and storage providers, interact through the allocation and spending of DataCap. Notaries retrieve DataCap in batches and then allocate it to trustworthy clients that spend the DataCap to fund storage deals. Storage Providers that receive DataCap receive a 10x boost to their quality-adjusted power for the storage space offered in that deal, which increases their block reward share in the network. This creates a mechanism that incentivizes all participants to make Filecoin more useful. Currently, users who use Filecoin plus still have a misunderstanding of the current definition.To make both Data Provider and Storage Provider better understanding, Bytebase created these new terms to standardize the use of Filecoin plus.

**\#The Proposal**
This recommendation includes explanations of common terms used in Filecoin Plus which were collected from partners.
The goal is to make people better understanding Filecoin Plus when people talk about this project.

**\#The New Terminology Mapping**

**Filecoin Plus project terminology explanation Mapping**

| **Terminology（****Chinese****）** | **Terminology（English）** | **Abbreviations** | **Explanation**                                              |
| ---------------------------------- | -------------------------- | ----------------- | ------------------------------------------------------------ |
| 数据伙伴                           | Data Partner               | DP                | 专注发展数据主体，帮助数据主体了解和认知Filecoin Plus项目，在获得授权后帮助其登陆存储网关平台（如bytebase.cn等）并协助上传真实有效数据，调试上传API参数，同时帮助数据主体对接和寻找数据存储提供方，规划存储策略，解决存储订单落地的各种疑问，包括但不限于fil汇兑相关的事宜。 |
| 数据主体                           | Data Owner                 | DO                | 合法拥有数据的机构、组织或公司，有数据存储需求，一般通过传统公有云存储或私有云存储解决存储需求。 |
| 真实数据                           | Real Data                  | RD                | 包括但不限于视频，图片，音频，文本、数据库文件，镜像等形态和格式。有存储意义和价值的数据，理论上都可以被定义为真实数据，真实数据不一定都是公开数据（该词条对标Filecoin网络中由系统生成的灌装数据） |
| 验证数据                           | Validation Data            | VD                | 真实数据中，经Filecoin Plus指定全球24个公证人验证过的部分数据。目前验证数据占真实数据的比重还比较小。 |
| 验证额度                           | Data Cap                   | DC                | 由Filecoin Plus公证人授予的，通过Filecoin节点钱包地址所承载的一个或多个额度。验证额度通过该节点地址的秘钥所管理，拥有验证额度的节点地址，在完成和数据存储提供方节点的存储交易时，会消耗自身对应的Datacap额度。 |
| 灌装数据                           | Junk Data                  | JD                | 由Filecoin系统自动生成的灌装数据，数据存储提供方节点在存储灌装数据时，可获取基础的Token激励 |
| 原值算力                           | Raw Power                  | RD                | 由总数据容量产生的算力（与该节点的存储空间实际消耗对应），是灌装数据和验证数据之和。 |
| 验证算力                           | Validation Power           | VP                | 验证数据在封装后，所产生的约等于验证数据存储容量十倍的算力。 |
| 奖增算力                           | Extra Power                | EP                | 验证数据在封装后，所产生的约九倍数据容量大小的纯新增算力。奖增算力是Filecoin Plus项目最主要的激励内容。 |
| 调整算力                           | Adjusted Power             | AP                | 原值算力与奖增算力之和，俗称有效算力。是Filecoin浏览器所呈现的最核心参数之一，是数据存储提供方节点获得Token激励的基础凭证。有验证数据封装的节点，调整算力会与原值算力产生差异。 |
| 发单地址                           | Deal Address               | DA                | 拥有验证额度的节点钱包地址，一般由f1XXXX或f3XXXX的代号构成。通过输入节点钱包地址，可在www.bytebase.cn首页查询实时DC额度。 |
| 节点地址                           | Node Address               | NA                | 数据存储提供方节点的地址，一般由f0XXXX的代号构成。           |
| 文件副本                           | File Copies                | FC                | 真实数据在Filecoin网络中的备份，由交易的存储策略决定（每个文件副本都将消耗与之容量对应的验证额度）。 |
| 节点机房                           | Node IDC                   | NI                | 封装和存储的数据存储提供方节点机房。                         |
| 网关机房                           | Gateway IDC                | GI                | 部署冰塔数据网关服务器的IDC机房。建议与节点机房一致，以优化网络传输消耗。 |

All above explanation we show you about Filecoin Plus terminology to help you understand them more precisely.

**\#What content assets will be updated？**
We will start using the new terminology. We also suggest to update the following websites and assets and promote the new terminology where possible.

- github /filecoin-project
- Bytebase website
- slack
- and other ecosystem tools

**\#The journey ahead**
Filecoin Plus aims to enable the demand side of the Filecoin network and maximize the amount of useful storage on Filecoin by adding a layer of social trust to the network and introducing a novel resource called DataCap. Clients looking to onboard storage onto the network apply to community-selected Notaries to receive DataCap, which can be used to incentivize storage providers to take storage deals.

**Comment by kaitlin-beegle** [comment]
Hey @swatchliu! Thanks so much for putting this together. 

To clarify, does this FIP **_1) propose new terminology_** or does it **_2) suggest a mapping of existing terms from English to Chinese_**? 

If the first is correct, can you please explain exactly which terms are being newly suggested, and why these ought to be codified as official terminology? 

If the second is correct, we should add an English explanation of each word as well.  I'd be happy to help with this, if you'd like.

**Comment by galen-mcandrew** [comment]
@swatchliu thanks for this proposal! Would you be interested or available to present in a Notary Governance call? https://github.com/filecoin-project/notary-governance/issues/226

**Comment by sapirmelton034621** [comment]
Wow, I think that it's a good proposal！

**Comment by redickstone000243** [comment]
Great!

**Comment by hunasdetunikolert** [comment]
Oh it helps us to understand. Nice

**Comment by swatchliu** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/ericl/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/ericl/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/ericl/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=ZH-CN style='tab-interval:21.0pt;word-wrap:break-word;text-justify-trim:
punctuation'>




Terminology（Chinese） | Terminology（English） | Abbreviations | Explanation
-- | -- | -- | --
数据伙伴 | Data Partner | DP | Focus on finding   data owners and help them to understand the Filecoin Plus.        Meanwhile, help   data owners to find data storage providers, make storage strategies, and   solve various questions about storage in Filcoin and rewards from Filecoin.       Upload data with   data owner's authorization, help data owners    log in to storage platforms (such as bytebase.cn, etc.)
数据主体 | Data Owner | DO | Institutions,   organizations, or companies that legally own data. They use public cloud or   private cloud storage.
真实数据 | Real Data | RD | Includes but is not limited to videos, pictures, audios, texts, images, database files, etc.        The data stored by human beings   can theoretically be defined as real data, and real data is not necessarily public   data (this entry corresponds to the junk data generated by the system in the   Filecoin network)
验证数据 | Validation Data | VD | The data was verified by   notaries in Filecoin designated by Filecoin Plus.
验证额度 | DataCap | DC | Granted by the   Filecoin Plus notary. One or more quotas are carried by the Filecoin miner address. The DataCap is managed by the private key of the miner address. Miner address with the DataCap will consume itself   when completing the storage deal with the storage provider node.
灌装数据 | Junk Data | JD | Junk data is   automatically generated by the program called "louts", the storage   provider can obtain token regards when storing the junk data.
原值算力 | Raw Power | RD | The power is generated   by the total hard disk capacity. It is the sum of the junk data and the validation data.
验证算力 | Validation Power | VP | After the validation data   is sealed, the generated power is approximately equal to ten times the   storage capacity of the validation data.
奖增算力 | Extra Power | EP | After the validation data   is sealed, the additional 9X power of the data capacity will be given to   the storage provider. Extra power is the most important incentive of the   Filecoin Plus project.
调整算力 | Adjusted Power | AP | The sum of raw   power and extra power is the basic proof for the storage providers to obtain a Token reward. For storage   providers with sealed validation data, the   adjusted power will be different from the raw power.
发单地址 | Deal Address | DA | The wallet address   with DataCap like f1XXXX or f3XXXX. By entering the miner wallet address, you can check the   DC by key in the wallet address on the www.bytebase.cn
节点地址 | Node Address | NA | The node address of   the storage provider like f0XXXX
文件副本 | File Copies | FC | The backup of real   data in the Filecoin network. It is determined by the storage strategy  (each file copy will consume the DataCap   capacity).
节点机房 | Node IDC | NI | Storage providers'   IDC
网关机房 | Gateway IDC | GI | Data gateway servers‘ IDC




</body>

</html>

**Comment by swatchliu** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/ericl/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/ericl/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/ericl/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=ZH-CN style='tab-interval:21.0pt;word-wrap:break-word;text-justify-trim:
punctuation'>




Terminology（Chinese） | Terminology（English） | Abbreviations | Explanation
-- | -- | -- | --
数据伙伴 | Data Partner | DP | Focus on finding   data owners and help them to understand the Filecoin Plus.        Meanwhile, help   data owners to find data storage providers, make storage strategies, and   solve various questions about storage in Filcoin and rewards from Filecoin.       Upload data with   data owner's authorization, help data owners    log in to storage platforms (such as bytebase.cn, etc.)
数据主体 | Data Owner | DO | Institutions,   organizations, or companies that legally own data. They use public cloud or   private cloud storage.
真实数据 | Real Data | RD | Includes but is not limited to videos, pictures, audios, texts, images, database files, etc.        The data stored by human beings   can theoretically be defined as real data, and real data is not necessarily public   data (this entry corresponds to the junk data generated by the system in the   Filecoin network)
验证数据 | Validation Data | VD | The data was verified by   notaries in Filecoin designated by Filecoin Plus.
验证额度 | DataCap | DC | Granted by the   Filecoin Plus notary. One or more quotas are carried by the Filecoin miner address. The DataCap is managed by the private key of the miner address. Miner address with the DataCap will consume itself   when completing the storage deal with the storage provider node.
灌装数据 | Junk Data | JD | Junk data is   automatically generated by the program called "louts", the storage   provider can obtain token regards when storing the junk data.
原值算力 | Raw Power | RD | The power is generated   by the total hard disk capacity. It is the sum of the junk data and the validation data.
验证算力 | Validation Power | VP | After the validation data   is sealed, the generated power is approximately equal to ten times the   storage capacity of the validation data.
奖增算力 | Extra Power | EP | After the validation data   is sealed, the additional 9X power of the data capacity will be given to   the storage provider. Extra power is the most important incentive of the   Filecoin Plus project.
调整算力 | Adjusted Power | AP | The sum of raw   power and extra power is the basic proof for the storage providers to obtain a Token reward. For storage   providers with sealed validation data, the   adjusted power will be different from the raw power.
发单地址 | Deal Address | DA | The wallet address   with DataCap like f1XXXX or f3XXXX. By entering the miner wallet address, you can check the   DC by key in the wallet address on the www.bytebase.cn
节点地址 | Node Address | NA | The node address of   the storage provider like f0XXXX
文件副本 | File Copies | FC | The backup of real   data in the Filecoin network. It is determined by the storage strategy  (each file copy will consume the DataCap   capacity).
节点机房 | Node IDC | NI | Storage providers'   IDC
网关机房 | Gateway IDC | GI | Data gateway servers‘ IDC



<p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>


</body>

</html>

**Comment by keseyjeanelle52** [comment]
Good job!

**Comment by Yolandeyi** [comment]
clear

**Comment by Yolandeyi** [comment]
It's cool!

**Comment by Xavieraie** [comment]
I've read it carefully.

**Comment by zohracharles** [comment]
It's worth reading.

**Comment by anelajennings** [comment]
clear and concise

**Comment by gokhalesantos550187** [comment]
good idea!

**Comment by hyltonturner** [comment]
good

**Comment by magelinewesthofer15** [comment]
Well done. These words are very suitable to use.

**Comment by emilcemalley04** [comment]
NICE

**Comment by kaitlin-beegle** [comment]
Hey @swatchliu! I joined the Filecoin+ community governance call this morning and confirmed that this proposal does not need to be a FIP. 

If it proposed _changing existing terminology_ (as was the case with FIP0018, changing 'miner' to 'storage provider') a FIP would be needed. However, this proposal seems to codify existing terminology and map it between languages.  As such, this is a proposal for new documentation, which doesn't need community consensus in order to be codified. 

That said, this is a great tool- folks already seem quite excited about it! 

@galen-mcandrew or @dkkapur - any suggestions as to where this doc should live, or what steps are needed to make this an accessible resource for the Filecoin+ community?

**Comment by kaitlin-beegle** [comment]
Closing as this does not require a FIP.  I have confirmed with @galen-mcandrew that the FilecoinPlus team will manage materials related to terminology.
