### ISSUE TITLE
FIP Workflow Improvement

### ISSUE THREAD

**Issue by iand** [filecoin-project/FIPs#16]
The [current process](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md) requires a pull request to be opened before the FIP number is assigned which requires the author to guess the next number the editor will assign with possible conflict (e.g. https://github.com/filecoin-project/FIPs/pull/13) or use a temporary filename (https://github.com/filecoin-project/FIPs/pull/9). This is going to get messier as the volume of proposals increases.

I propose that FIP-1 be amended to require a Github issue to be opened first, containing the substance of what would become the WIP version of the FIP. The FIP Editor reviews and assigns a FIP number. Then the author proceeds to open a PR for the FIL to put it in WIP status.

**Comment by anorth** [comment]
SGTM

**Comment by momack2** [comment]
This was discussed and we agreed to trial it for the next few FIPs in today's Core Devs weekly: https://www.youtube.com/watch?v=58b8TY9LJaM -- @iand do you want to make a PR to FIP-0001?

**Comment by kaitlin-beegle** [comment]
Hey @iand! I'm cleaning up old FIP issues and noticed that language in FIP-0001 remains unchanged.  This is an old discussion post, but the idea remains a good one :) 

Would you mind submitting the language change as a PR, or else provide an update? I would also be happy to make this change for you, but wanted to give you the opportunity to do so first.

Thanks!

**Comment by kaitlin-beegle** [comment]
Updating FIP-0001 to incorporate this change, and then closing the request. 

This changes seems to have been de facto adopted so I will write it into the FIP for the purpose of clarification.
