### ISSUE TITLE
Require a storage provider to set the PeerId when the Multiaddr is set.

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/FIPs#161]
For deal making, a client needs to know the storage provider's PeerId, and then using the DHT to resolve the associated PeerID to the miner's Multiaddr to exchange data and eventually get data stored in the Filecoin network by making deals.

Currently, a storage provider can set Multiaddr without having a PeerId set onchain which makes them less discoverable in the network for deal making. Require a storage provider to set the PeerId when the Multiaddr is set to resolve this issue.

**Comment by kaitlin-beegle** [comment]
Hey @jennijuju, sounds great.  This also seems like a relatively light technical lift- do you envision shipping this potential FIP during the Fall 2021 Lotus implementation update? 

CC: @arajasek

**Comment by jennijuju** [comment]
> Hey @jennijuju, sounds great. This also seems like a relatively light technical lift- do you envision shipping this potential FIP during the Fall 2021 Lotus implementation update?
> 
> CC: @arajasek

Yes - If it’s approved  by the core devs, I think it makes sense to include it  in the next network upgrade

**Comment by jennijuju** [comment]
Fip draft created https://github.com/filecoin-project/FIPs/pull/162

**Comment by jennijuju** [comment]
https://github.com/filecoin-project/FIPs/pull/162#issuecomment-923089359
