### ISSUE TITLE
Remove vesting from PreCommitSector and ConfirmSectorProofsValid

### ISSUE THREAD

**Issue by anorth** [filecoin-project/FIPs#18]
**Background**
Vesting is processed via `State.UnlockVestedFunds`, which is called from `PreCommitSector`, `ConfirmSectorProofsValid`, `WithDrawBalance` and the deadline cron. The original motivation for computing vesting on sector commitment is so that any vested funds could be used for pre-commit deposit or pledge.

The vesting table is quantized to 12-hr increments. Since vesting is processed in the deadline cron every 30 minutes, the calls during sector commitment almost always achieve nothing. The most it could achieve is to accelerate a release by 30 minutes.

Processing reward vesting is quite expensive as it loads and stores a sizeable array for the vesting table. For high-scale miners, committing many sectors per deadline (or even per-epoch), this represents a sizeable portion of total gas cost and chain bandwidth consumption.

**Proposal**
Remove vesting from `PreCommitSector` and `ConfirmSectorProofsValid`, leaving it to the deadline cron. If necessary, the miner's owner can trigger vesting via `WithdrawBalance` (possibly with an argument of zero).

This will reduce the gas consumption of these methods substantially, freeing up chain bandwidth for other messages, reducing gas costs, and/or improving validation speed.

First proposed in https://github.com/filecoin-project/specs-actors/issues/1258

**Comment by anorth** [comment]
I will draft a FIP PR for this. @dignifiedquire @whyrusleeping if this seems reasonable could you please assign a FIP number (see #16)?

**Comment by momack2** [comment]
More chain throughput (via lower gas usage) sounds great! The slight delay in miner rewards (which can be solved by manually triggering `WithdrawBalance` seems like a reasonable cost for such an improvement. 👍

**Comment by anorth** [comment]
Closed by #19

**Comment by momack2** [comment]
Keeping this open as a place for discussion on FIP-0005

**Comment by nicola** [comment]
I think this can be closed now that it's accepted, correct? https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0005.md
