### ISSUE TITLE
Datacap Management

### ISSUE THREAD

**Issue by kaitlin-beegle** [filecoin-project/FIPs#257]
### Discussed in https://github.com/filecoin-project/FIPs/discussions/251

<div type='discussions-op-text'>

<sup>Originally posted by **jennijuju** November  9, 2021</sup>
**Note: this discussion is created based on the current state of the art of Filecoin plus program as of Nov 9, 2021. It is under the assumption of the high level principles and the mechanism of the program will stay unchanged for the next 4-6 months(to be more specific, I'm not factoring in how FVM may unlock more options and flexibility for the program). 

[Filecoin plus](https://github.com/filecoin-project/notary-governance),  introduced by [FIP-0003](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0003.md) is a governance program aims to get valuable data verified and onboarded to the filecoin network.

As a part of the program mechanism, there are _notaries_ as the verifiers to evaluate the clients and their data, then grant a certain amount of _datacap_ to the qualified clients' filecoin wallet. _Datacaps_ are like a client credit quote imho. Then clients can make _verified deals_ using the datacaps and enjoy cheaper storage service offer. More details about the program can be found[ here](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0003.md)

The current [verifreg actor](https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/verifreg/verified_registry_actor.go) has the following functionalities:
- RKH to add/remove verifiers(notaries) 
- verifiers add verified clients, as notaries grant datacap to clients after off-chain manual verifications

## Proposal
**I'd like to start a discussion about adding two more features:**
- TransferDatacap
- RemoveVerifiedClient

### TransferDatacap

A client may send a `TransferDatacap` message to transfer remaining datacap to a different wallet. One or more notaries*  should approve the message before the datacap is transferred. 

One of the use cases here would be a client with valuable data has been granted X datacap, however, then if they decided to use data broker like [estuary](https://estuary.tech)/.storage for easier deal making experience, they should have the option to transfer the datacap to the wallet account that is registered or used by the data broker so the data broker may make the deals on their behalf.

**Open question**
- As the filecoin plus program is based on the verification then a trust relationship between notary, clients and network participants,  do we need one or more notaries to approve the transfer if the client has been verified already? 

### RemoveVerifiedClient

According to filecoin plus statics shown [here](https://filplus.d.interplanetary.one/statistics), only 9.53% of the total datacap and 0.5% of the total LDN datacap was actually used in verified deals. I think we should first try to figure out why the clients requested datacap but not onboarding data. But also, have an option to remove inactive verified clients would be nice to avoid potential future storage market manipulation with malicious usage of datacap.

Be able to remove malicious clients that were reported as a fraud or one cheating the system would be useful once the filecoin plus has fraud audit mechanism.

**Open question**
- Should there be an expiry on datacap? If so, how long should that period be?
- Should datacap get revoked from an inactive client gradually over a period of time or at once(remove the wallet from verified client client list)?</div>

**Comment by dkkapur** [comment]
Note that the FIP draft actually only addresses the RemoveVerifiedClient aspect of the original discussion topics put forth by @jennijuju. The FIP was scoped to address removing DataCap from a client address (which in turn, removes VerifiedClient status if the DataCap balance is 0).

**Comment by kaitlin-beegle** [comment]
This FIP officially moved to 'accepted' status on 1/24! Closing issue!

**Comment by beatlesgogo** [comment]
So how long is the period?
We are looking forward to store our data, and are looking upon to related rules.

**Comment by dkkapur** [comment]
@beatlesgogo - is this wrt to the implementation or the period after which Fil+ notaries may want to remove DataCap from an inactive client?

**Comment by beatlesgogo** [comment]
The period ter which Fil+ notaries may want to remove DataCap from an inactive client.
