### ISSUE TITLE
Dead links & doubling of FIPs list

### ISSUE THREAD

**Issue by dud1337** [filecoin-project/FIPs#286]
## Dead links
The first two links on this page are dead:
https://fips.filecoin.io/proposing/

## Contradictory doubling of FIPs sections at end of page
https://fips.filecoin.io/
There appears to be two "FIPS" sections on this page. The second section's links are broken too.

None of these issues will be difficult to fix.

**Comment by dud1337** [comment]
After some discussion with @kaitlin-beegle I have some background on the repo's history and know what to do to fix these issues. Should be relatively simple.

**Comment by kaitlin-beegle** [comment]
Thanks for your help, @dud1337! Closing this issue; will merge PR when it comes through.
