### ISSUE TITLE
Discussion: Rebalance Gas Charges 1

### ISSUE THREAD

**Issue by Kubuxu** [filecoin-project/FIPs#31]
Due to optimizations and evolving software I propose changing Gas charged for following operations:

| Call Name | Old Gas | New Gas | Change |
|---|---|---|---|
|OnVerifyPostBase|374296768 *|117680921|-68%|
|OnVerifyPostPerSector|42819 *|43780|+2%|
|OnIpldGet|75242|114617|+52%|
|OnIpldPutBase|84070|353640| +320%|
|StorageGasMultiplier| 1000| 1300|+30%|

\* - OnVerifyPost currently has arbitrary 2x discount applied, Old Gas numbers are including this discount, New Gas do not

Above changes can be divided into four categories:
- Reductions in the cost of verifying proofs due to improvements to proof-verification times.
- Increase in cost of accessing the storage due to increased size of statetree and thus the index size of the storage making it slower. On Lotus side, we are working on improving this and if we see results in the next round of gas rebalancing cost of accessing the storage might decrease.
- Increase in flat cost of saving objects, we've missed the cost of flushing newly created objects from memory to disk when pricing OnIpldPut, the increase is due to the inclusion of that cost in OnIpldPut.
- Increase in per-byte storage cost. Size of the state tree and storage required for running nodes grows at a very fast pace. We hope that increase to storage cost will incentivise optimizations like compacting AlllocatedSectors bitfield in miners or using ID addresses in messages.

**Comment by Kubuxu** [comment]
This results in the following changes for common operations:
```
PreCommit: 17539751 -> 26320256
ProveCommit: 40808085 -> 17048680
Whole Sector: 58347836 -> 43368936
WindowedPost Full Parition: 510899161 -> 275871753
```

**Comment by pooja** [comment]
Does this do anything for publishing storage deals? Would be great if we could help reduce the costs there, otherwise risks passing on high gas fees to users through increased ask prices or restricts the number of storage deals that make it through.

**Comment by flyworker** [comment]
Get block reward is still so attractive to the CC miners, the flood in pledging activity make the base fee increased

**Comment by Kubuxu** [comment]
@pooja publishing storage deals is on-chain bookkeeping that doesn't call Syscalls different than related to storage, thus this change does not decrease gas cost of that message.

The main way to decrease the cost of publishing storage deals is to somehow optimize how that operation is peformed in actors.

**Comment by Kubuxu** [comment]
The proposal changed a bit to ommitt changes to `GasOnSubmitVerifySeal`.
