### ISSUE TITLE
Discussion: Consolidate sectors into one proving deadline until deadline is full

### ISSUE THREAD

**Issue by rjan90** [filecoin-project/FIPs#32]
**Problem**
If a miner finishes sealing a sector during a challenge window, the sector gets assigned to the next deadline. This leads to sectors spread across multiple deadlines, even if a deadline is not filled with 2349 sectors.

Example: 

```
deadline  partitions  sectors (faults)  proven partitions
0         1           686 (0)           0
1         1           13 (0)            0
2         1           9 (0)             0
```
This leads to unnecessary messages on the chain, and also unnecessary fees paid by miners, especially when wPoSt-fees are as high as they are in this time of writing.

**Proposed Solution**
In a earlier discussion on [Slack](https://filecoinproject.slack.com/archives/CHMNDCK9P/p1602428887018300), nickle proposed two solutions:

1. Have a function that consolidates sectors
2. Change sector allocation to not leak into other sectors + one-time sector consolidation.

**Discussion**
Nickle noted that solution 1 might be messy regarding security.

**Comment by anorth** [comment]
"Multiple" here is at most three, based on at most two deadlines being excluded from selection. They are excluded so that partition membership does not change while a Window PoSt proof might be in computation.

Are there any proposals for such a change to sector allocation? Some straw-people:
- Deny prove-commit if the target partition is currently excluded; miner has to wait until deadline passes
- Allow partitions to change at any time, even if that could invalidate an in-flight Window PoSt

**Comment by nicola** [comment]
I like the proposal from @rjan90, in particular option 2.

The main constraint that I have is that a sector should be proven every 24h. With this in mind I think we could do the following changes: if a sector is assigned to the current deadline, assign it to it, but do not challenge it instead.

I think that given the fact that power is only added at first windowpost, the above constraint may not be relevant anymore (cc @irenegia)

**Comment by anorth** [comment]
Avoiding challenging a sector assigned to a deadline would make for some moderately complex state tracking in an already complex area. A simpler way to achieve the same outcome is just to deny ProveCommit while the deadline is ineligible. The miner just has to wait until the window passes. Mining software could be fairly simply modified to withhold ProveCommits until the deadline is clear. Of course, mining software could do this *today* with no change required to actors. The question becomes whether to enforce this policy for everyone as a protocol rule, or allow some miners (maybe the high-growth ones) to prove-commit when they choose, according to their own cost/benefit structures.

This would follow our general design principle of putting as much complexity outside the chain as possible.

Now that I've written this, I feel pretty strongly that the blockchain should not enforce policy liek this, and this is instead a feature request for Lotus. Miner's can locally modify their scheduler to do the same today.

**Comment by rjan90** [comment]
I can agree that it's better to keep complexity out of the chain. Regarding the question of enforcing this policy, I think it should be strongly encouraged by the network, as it seems rational from a cost-perspective, and also a technical perspective, to reduce messages on chain.

Based on the discussion, I'll close this issue, and instead make it a feature request for Lotus.

**Comment by anorth** [comment]
Thanks, I'm really glad we had this discussion!

**Comment by zixuanzh** [comment]
cc @magik6k @jennijuju

**Comment by karalabe** [comment]
I'm not sure it's fair to close this issue.

> Miners can locally modify their scheduler to do the same today.

Myeah, no. Miners don't have the knowledge to do that. Even if they did, you can't fix existing split paritions on chain, so you're saying small miners should suck it up? E.g. I had 3 partitions as of yesterday, one with 500 sectors, one with 15 and one with 2. How should I fix this?

**Comment by momack2** [comment]
I think this is a feature request to lotus to help all miners avoid many
partitions by default (but make it configurable at a protocol level if some
miners want to modify this default). Agree that what lotus-miner does out
of the box should be the best thing for most miners vs requiring deeper
modifications. My understanding is the current proposal is to fix defaults
going forward instead of adding complicated methods to enable moving
proving periods around.

**Comment by ribasushi** [comment]
@rjan90 @karalabe Did you guys follow up with a lotus-side ticket? A starting point could also be a doc addition expkaining the tolerances of the system: if you want a sector to be included in your current unfilled deadline, the prove commit *must NOT* land between X and Y epochs of that deadline ( I do not know X and Y off the top of my head )

**Comment by ZenGround0** [comment]
@arajasek says:

> [this] is basically impossible to do (or rather to guarantee), right? Because we basically have no idea when messages will actually land on chain.

**Comment by NSC-FIL** [comment]
This issue came up in our recent MinerX meeting. It was also mentioned previously in regard to finding a way to decrease congestion and high base fees: 
"We really don't need so many CC sectors. (We have already paid too much for future. Hardwares of today is not the best of tomorrow. We should protect the Earth.) High BaseFee makes verified deals(10x power) not so attractive. We should encourage real/verified deals more and CC sectors less." 
A solution will help smaller miners manage their operating costs better.

**Comment by AthenaPoolOfficial** [comment]
There are tow question that worth discussing.
1. If we want to change the  determined deadline of the sectors that have already submitted ProveCommit,  we will have to fix a lot of complicated programs. We have reservations about this.
2. We may focus on the uncommitted ProveCommit, and try to integrate them into one deadline.
Specification: We can test the D-value between the current wdClose epoch and the current epoch when we are going to submit the ProveCommit ,but back-out the submission when the D-value is less than a certain value that we appoint.
At the same time, we make a judgement about the remaining epoch of the PreCommit before it expires, and if the epoch is less than certain value,we should submit the ProveCommit directly without the test we mentioned above.
All in all, the consumption of WindowPost remains a low level, and the significance of merging deadline may not be as great as we expect.

**Comment by kaitlin-beegle** [comment]
Just reached out to @ZenGround0 on Slack to ask for clarification about the node -side updates that may address this issue. 

@AthenaPoolOfficial, if your team is working on this issue or is interested in pursuing a FIP here, I would recommend that you open up a new issue in the [FIPs Discussion Forum](https://github.com/filecoin-project/FIPs/discussions/categories/enhancements-technical)! Going forward, this is where FIP conversations will live.  Outstanding items in this Issues log will be deprecated.

**Comment by rjan90** [comment]
Closing this issue, as FIP discussions are moving to the [FIPs Discussion Forum](https://github.com/filecoin-project/FIPs/discussions/categories/enhancements-technical).
