### ISSUE TITLE
Cancellation of filecoin pledge

### ISSUE THREAD

**Issue by chinamgy** [filecoin-project/FIPs#394]
Due to the sharp drop in the price of filecoin and China's unfriendly mining policy, I apply for community discuss and revise the 540 day lock up period for filecoin pre pledge. To make the pre pledge redemption of filecoin optional. For example, if the pledge is redeemed in advance, 20% of the pledge filecoin needs to be directly burned. I hope more people candiscuss it. Chinese minner storage providers are willing to vote on this issue. Please do not delete our appeal.

**Comment by anorth** [comment]
Please open a discussion topic instead: https://github.com/filecoin-project/FIPs/discussions. I'm willing to engage, but partly-formed ideas and requests go in the discussion board rather than issues/PRs.
