### ISSUE TITLE
Pausable mining

### ISSUE THREAD

**Issue by vht210** [filecoin-project/FIPs#48]
As holiday seasons approaching, I would propose a new cool feature for Filecoin, Pausable Mining. 

**Why do we need it:**

- To reduce stress from miners, to allow miners have more time with loved one instead of staring at PC for windowPost and typing mpool replace.
- Reduce traffic therefore reduce basefee.
- Keep small miners alive little bit longer until the basefee is cool down.
- Upgrading system, relocating miners, recover hardware failure without too much stress about the time.

**So how does it work:**

Miners send message to the chain to inform about its break time. Pausable mining is a fix period (1-2 week or a number of epoch), during pausing period, miner still need to participate in the network but less strictly (1 WindowsPost in 72 hours, pelnaty after 2nd missing WindowPost). The pausing miner will not able to mine any block, accept any deals or do CC sector. However, it still allow for retrieval deals.

**Comment by xinaxu** [comment]
Not sure if its a good idea but during holiday season, there would be more traffic to some business, say Amazon. Assume they are now relying on miners. Allow miners to reduce commitment and responsibility isn't good for business. Also, there can be risk of miner strike that significantly reduce the network reputation without much penalty.

**Comment by jennijuju** [comment]
FIP0009 was introduced as a stop-gap to relieve the "stress" back in December.
