### ISSUE TITLE
Introduce FIP to exempt Window PoSts from BaseFee burn

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/FIPs#52]
This is a discussion issue for [#51](https://github.com/filecoin-project/FIPs/pull/51) ([Rendered](https://github.com/filecoin-project/FIPs/blob/e17c914f44bbff224893fe8928203f9d7c6b6d52/FIPS/fip-claus.md)).

**Summary:** Exempt direct `SubmitWindowedPoSt` messages that execute successfully from base-fee burn (i.e., don't burn `baseFee*gasUsed`).

If a miner sends a direct on-chain message to a miner actor's "SubmitWindowedPoSt" method, and the message executes successfully, immediately "refund" all the burned gas, instead of just refunding the overestimation. However, overestimation penalties, gas premium, etc. still apply.

**Motivation:**

This proposal is a short-term stopgap to reduce the impact of rising base fee on continuously proving existing storage. In principle, BaseFee*GasUsage is burned to compensate the network for the resources consumed by messages and ensure incentive alignment. However, SubmitWindowPoSt is a required message to continue mining operations in Filecoin. 

* Long-term solutions for reducing the cost of Window PoSt include https://github.com/filecoin-project/FIPs/issues/42.
* Long-term solutions for reducing chain congestion include https://github.com/filecoin-project/FIPs/issues/49, https://github.com/filecoin-project/FIPs/issues/50.

Unfortunately, such long-term solutions are complex and cannot be properly implemented and tested on the required timescale (before the holidays). This proposal is a short-term mitigation until those solutions are ready.

**Comment by ec2** [comment]
Without the basefee, wouldn't WindowPost messages become super cheap making the network susceptible to spam attacks where an attacker fills up blocks with WindowPost? AFAICT, there is no penalization for submitting faulty WindowPost.

**Comment by Shekelme** [comment]
Sounds excellent for small miners.

**Comment by shawnp0wers** [comment]
This is an appreciated stop-gap, and perhaps something that might be considered long term for new miners who haven't crossed the threshold to actually mine. (The wdpost burn penalizes the smallest miners the most, as it takes them much longer to build up the sealed storage in order to mine, but they still wdpost every day)

Still -- this will be a much needed financial relief across the board. Thank you.

**Comment by nicola** [comment]
I don't think it can be changed to only work for new miners.. large miners can always distribute power across smaller "new" miners.

**Comment by shawnp0wers** [comment]
> I don't think it can be changed to only work for new miners.. large miners can always distribute power across smaller "new" miners.

I'm not sure if that was in reply to my comment -- but I meant specifically during the "you don't have enough sealed to mine blocks" phase. There would be no advantage to distributing to "new" miners, because less than 10TB can't mine at all.

**Comment by nicola** [comment]
Ah, yes @shawnp0wers I think that's a very good idea. I know someone was interested in writing an FIP where small miners are exempt or have reduced fees when in that phase, this idea should be added to that!

**Comment by jennijuju** [comment]
Closed by https://github.com/filecoin-project/FIPs/pull/51

**Comment by goeb36** [comment]
@goeb
