### ISSUE TITLE
Discussion about `maximum sector lifetime extending`

### ISSUE THREAD

**Issue by askender** [filecoin-project/FIPs#54]
## Problem
Maximum sector lifetime is 540 days for now, there is no way to extend a deal lifetime now.
It is a little early to discuss about the implementation, but a design for it is needed.

## Solutions 
- A: Change nothing. Client need to resend the data and miner need to re-sealing the sector. It is a waste of resource. And the User experience is not good.
- B: Support the feature of `extend a deal lifetime` someday, and plan it in the roadmap.
- C: Wait and see.  No need to design it now.
- D: Hope to hear your ideas/thoughts.

**Comment by jbenet** [comment]
- Yeah, we should discuss and implement well before it's needed. the sooner we have a protocol design for it, the safer this will all be.
- this was always hoped for, and i think most/all of the community will greatly support sector lifetime extension.
- there's some problems to work out, but this shouldn't be too difficult of a protocol change.

**Comment by jbenet** [comment]
cc @nicola @zixuanzh

**Comment by askender** [comment]
Glad to see https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0014.md is passed and implemented.  
But I still wonder why we choose 5 years?   `SectorMaxLifetime: EpochsInFiveYears`   
What will happen after 5 years? What if the client want to store dataset for a longer time?  I didn't find the docs about the design principles.
Besides, it reminds of the GitHub Arctic Code Vault.   How will we choose from the short term value and long term value?
And,  
- if a dataset is valueable, will other people have the rights to extend those deals/datasets? Crowdfunding of extend-SectorMaxLifetime or Crowdfunding of storing-data-to-more-miners?
- if a client upload a wrong data which should not be stored, what should the client do to stop the storing?
- If a data is stored in filecoin and not encrypted(any can found the hash/PieceCID to download them), what is the copyright of the dataset?(who have the rights to extend them and use them)
- If a dataset is stored for 5 years, and it should be important, but the metadata of the dataset is lost. What will happen? I am designing and building a web3 search-engine(retrieval-system) which will include ipfs and filecoin datasets. So I have a lot of question about this problem.
