### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by snissn** [filecoin-project/FIPs#559]
hey! 

I was reading the FIPs and i came across this webpage and all the links on the second half of this page are broken:

https://fips.filecoin.io/#fips

links like https://fips.filecoin.io/FIPS/fip-0049 fail with an error message like

`ipfs resolve -r /ipfs/bafybeiaih4myed3jcyxklshxud2wh7p2cb2wgblmtuz2464qezxlmyfzd4/FIPS/fip-0050: no link named "fip-0050" under Qma8MzAfojc6a21rGxzoh1AgxE1kCzvEBFjqAwrSjwFYnP`

**Comment by CluEleSsUK** [comment]
+1 
Even without using the IPFS extension it's not working
