### ISSUE TITLE
ChangeOwnerAddress support MultiSig Address

### ISSUE THREAD

**Issue by hexcola** [filecoin-project/FIPs#58]
We all know the **Owner Address** is the key of miner,  even we can delete owner address after we change owner address, but when we withdraw FIL or must keep owner address stay in the lotus for some reason, it's still dangerous.

**Comment by hyunmoon** [comment]
Some miners on custom code are paying fees from their miners' available balance.
This negates the need for the owner key to be present in wallet for daily operation.
Wish it was supported officially as an option.

**Comment by hyunmoon** [comment]
Owner key is designed to be required for initializing or withdrawing.
Neither multi-sig nor Ledger key can be used as an owner key at the moment.
https://github.com/filecoin-project/lotus/issues/5127

**Comment by hyunmoon** [comment]
Owner key is designed to be required for miner actor related tasks (Initializing, withdrawing, changing worker keys, peer ID, etc).
Neither multi-sig nor Ledger key can be used as an owner key at the moment.
These issues should be addressed in priority.
filecoin-project/lotus#5127

**Comment by jennijuju** [comment]
Agreed that we should support this in lotus soon. However, i dont think an FIP is necesssary for this. I created this [ticket](https://github.com/filecoin-project/lotus/issues/5287), @hexcola let me know if you think this should stay as an FIP.

**Comment by hyunmoon** [comment]
Didn't realize this is FIP repo.

**Comment by hexcola** [comment]
> Agreed that we should support this in lotus soon. However, i dont think an FIP is necesssary for this. I created this [ticket](https://github.com/filecoin-project/lotus/issues/5287), @hexcola let me know if you think this should stay as an FIP or we can close this.

as long as the core team hears us,  close this issue is totally fine.
