### ISSUE TITLE
Enable DataCap Top up for Filecoin Plus Client Addresses

### ISSUE THREAD

**Issue by jnthnvctr** [filecoin-project/FIPs#70]
### What exists today
- Clients can request a DataCap allocation to be made to a specific address by providing information (off-chain) to a Notary
- A Notary can make an allocation to that address to give the Client DataCap
  - For Clients, DataCap allocations are treated as a “one-time” gift card per address
  - This means that if an address has previously received DataCap it is ineligible to receive future DataCap allocations (as long as there is at least the minimum deal size worth DataCap remaining)
  - DataCap allocations are non-transferrable
 
The above creates an issue for the average client - if you receive an allocation of DataCap and end up with an amount that is less than enough to make a deal (e.g. 4GiB) and more than the minimum deal size, you will be unable to receive further allocations to your address. This can create unnecessary friction for users who might then be required to create a new address in order to continue making deals. 

## Proposed Solution
Client addresses should be able to receive additional DataCap allocations to a given address.

Cases to consider: 
- On-chain address, never received DataCap
  - No change from current mechanism - Client should be able to request DataCap to this address.
- On-chain address, received DataCap previously
  - Client should be able to request DataCap to this address again
  - DataCap should be treated as an addition to existing balance (Existing balance = existing balance + new allocation) 
 
It is worth also discussing how a client applying for DataCap from multiple Notaries may manifest - many of these solutions focus on process and tooling for Notaries, as what may appear as a race condition could also take the form of legitimate requests: 
- A client who needs 5TiB total applies to three Notaries (5TiB each), hoping to get approved by at least one of them quickly.
  - In the first case, it is expected that the Notaries would (in the course of due diligence) ask if the applicant had other pending requests.
  - When making the approval, the Notary should check the specific address (either in the public repo, block explorer, or natively in plus.fil.org) to verify when the last allocation was made.
    - In plus.fil.org - the aim is to have this appear in the same modal as a warning denoting when the last allocation was made, the size of the allocation, and the sender.
  - When in doubt, the Notary can also stagger their allocation (because addresses can receive multiple allocations) to ensure a Client is not receiving more than is due.
    - While a process is not established here, there are several possible ways that the Notary avoids the race condition: 
      - Announcing their intended action to the intended address to the other Notaries
      - Staggering their allocation such that the modal warning will pop up for others.
  - In the event that multiple Notaries simultaneously allocate the full amount (Client receives 10TiB+ of DataCap) - the Client has received more than they intended.
    - We anticipate this will be an unlikely event given:
      - Notaries are geographically dispersed (and only a few per region), so the likelihood of race conditions is quite low
      - In the event a Client receives DataCap, the Notaries individually would be following their allocation plans to ensure the Client is trustworthy.
      - Given the rigor of these plans, it is highly likely that someone who was worthy of receiving 5TiB would credibly be able to have applied twice in a row - the risk factor is relatively low.
  - A client who needs 15TiB total applies to three Notaries (5TiB each), hoping to get approved by each of them.
    - In this case, it is expected that all Notaries would all separately do their due diligence to arrive at a decision.
    - In the case of large scale allocations (e.g. PiB scale), it may require a higher degree of coordination across Notaries - this is something that would require more process to be defined.

### Potential Impact
- The previous reasoning for treating allocations as a “one-time” gift card was to mitigate the potential for abuse. 
  - The original reasoning was that by requiring Clients to request a new address each time they’d be limited in their allocation and ability to spend.
  - The additional friction was intended to slow down the speed of allocation and limit damages in the event of abuse or uneducated use of DataCap (allocating all to the same miner).
    - Given there was less known about DataCap allocations and how it would manifest, the approach was to bias towards increasing friction to reduce risk. 
  - However, this has a few practical implications: 
    - Malicious actors who want to acquire large amounts of DataCap simply need to spin up many addresses (which can be done trivially) 
    - Notaries trying to evaluate past Client allocations require the Client to self identify all their previous addresses
    - Legitimate actors (e.g. web3 devs) now need to manage the rotation of addresses for end users to be able to spend their DataCap. Rather than enabling legitimate users the ability to have a “default” address, they need to manage the rotation across an ever-increasing list. 
      - Notably when deal renewal is a thing (™) it’s also likely that the client will be using the same address as before - and will want to be able to spend DataCap to renew
- The above notably does not actually address the underlying issue: 
    - Because Notaries can’t necessarily know all the previous allocations a Client received AND because spinning up new addresses is the norm / trivial - the security benefits are minimal.
    - On the flip side, the friction introduced (and required implementation implications for legitimate actors) is quite high
- An added benefit - by normalizing having Clients have a “default” address they make deals from and receive DataCap to (which might also make them more eligible for higher DataCap allocations) we can build up a mechanism of credit / reputation from the Client.
- Other benefits:
    - Enabling reputation via longevity of wallet addresses
    - Security of dataCap since a smaller number of wallets need to be secured
    - Fund security (lots of wallets by the same party makes it harder for orgs to track their own funds)
    - Analytics for the same org getting allocations from multiple notaries.  (Some of the fraud vectors of creating multiple addresses still exist, but this proposal makes it easier for honest players to differentiate themselves).

### Open Questions
- Would having multiple notaries change the security implications here? 
  - I don’t think materially so - as it stands a Client could spin up two separate addresses and make two separate allocation requests to two different Notaries. From the perspective of a malicious actor, they might do this anyways if they’re trying to be undetected.
  - For legitimate clients, it’s possible you apply to multiple Notaries and independently they give you additional DataCap (more than what you require)
    - This can first be addressed with education of Notaries
    - Additionally, the UX in the Notary Dashboard can be modified to show
      - DataCap for the Client address in question
      - Time of last allocation
      - New DataCap
    - Given the small number of Notaries and limited allocations available, the risk factor is quite low
      - Open question might be whether we should also implement a deletion of DataCap (though this opens many questions about who should have this power, what limits to this power should exist, etc). 
  - Arguably having a reliable address (where a Notary could inspect previous spend from a Client), you give Notaries an additional metric of previous allocations that is less reliant on self-reporting.
  - Should the history of DataCap be stored on-chain? (presumably )
    - As of today you can trace the acquisition of DataCap (when it was granted) and how it was spent - so presumably with every address you can compute how much DataCap it had remaining at a given point in time.
    - In lotus-shed, you can see for the current point in time what is the DataCap balance
  - Alternative: Should there be a mechanism to link multiple addresses in a public way?  Does this transparency help?

**Comment by kernelogic** [comment]
The reason I have multiple PR open is I got no response for previous PR for over two month. For example:
https://github.com/keyko-io/filecoin-clients-onboarding/issues/83

**Comment by jnthnvctr** [comment]
@kernelogic  - I would tag the Notaries in the slack channel, this is the wrong place to discuss that.

**Comment by kernelogic** [comment]
No response by tagging either. Tried that.

**Comment by s0nik42** [comment]
Good proposition, it definitely make sense, I will give my 2cts : 

Client should have one notary; I see a lot of  drawbacks of having multiple notaries working on the same client 
- workload on notaries 
- risk of double allocation
- confusion
If a client needs 15TiB, it should not apply to 3 Notaries IMHO but to a unique notary and get successive datacap from that notary. 
If the notary is out of datacap then the client can go to another notary.

Datacap allocation History should include at least : 
- Allocation Date
- Notary name
- Client name
- Filecoin address 
- If possible url of the issue attached to that allocation
- Amount of the datacap allocated
- List of miners  the datacap was consume with.

Removing datacap : 
- Request should come from any notary and include motivation.
- 2 on 3 notaries (randomly taken) should validate the datacap removal  (including the one that allocated it)

**Comment by KaptinLin** [comment]
Client should be able to request DataCap to its address again, and he should be able to apply for DataCap from multiple Notaries. 
Some clients' data may come from all over the world, and restricting them to only apply with one notary will cause a lot of inconvenience
plus.fil.org should list all DataCap the client get from, If we can conveniently browse the client's historical allocations and the current application status, the notary can process the application fairly and efficiently.
Notaries can process applications fairly and efficiently.

**Comment by Fatman13** [comment]
+1 @kernelogic 

It is not apparent which review stage the notaries are on. More timely communications from notaries are much appreciated.

**Comment by kaitlin-beegle** [comment]
Closing due to FIP0012
