### ISSUE TITLE
Should we consider tagging segment and aggregate pieces differently ? 

### ISSUE THREAD

**Issue by Gozala** [filecoin-project/FIPs#835]
While working on [JS implementation](github.com/web3-storage/data-segment) of [FIP 0058](https://github.com/filecoin-project/FIPs/blob/master/FRCs/frc-0058.md) I do find that often you need out of bound signal for whether you are dealing with segment or aggregate Piece (CID).

Go implementation also had two different structs, presumably to be able to differentiate between them.

With [Piece V2](https://github.com/filecoin-project/FIPs/blob/master/FRCs/frc-0069.md) we are tagging CID as [raw](https://github.com/filecoin-project/FIPs/blob/master/FRCs/frc-0069.md#raw-codec) block. Perhaps we could tag aggregates with a different code ?

**Comment by kaitlin-beegle** [comment]
Hey @Gozala! This should be a discussion post, not an 'Issue'.  Transferring now :)

**Comment by kaitlin-beegle** [comment]
@Gozala - can you please open this in the Discussion Forum? Thanks!
