### ISSUE TITLE
Add a maintenance window flag for network upgrades and/or instability

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/FIPs#84]
Currently, network upgrades (and incidents like https://filecoin.statuspage.io/incidents/ffhr434cd14c) can temporarily reduce chain quality and, in some cases, cause miners to miss Window PoSts. This is mitigated by the fact that no penalties are paid for missed Window PoSt. Unfortunately, power that wasn't proven is still lost until the next Window PoSt.

# Proposal

Introduce a "maintenance window" flag that can be set for a range of epochs. Any deadlines that end within a maintenance window will not be penalized for missed Window PoSts.

## Implementation

1. Expose a `MaintenanceWindow() bool` function on the runtime. Implementations will return `true` from this function when a maintenance window is in-progress.
2. When processing an end-of-deadline cron event, if `MaintenanceWindow()` returns true, assume that _all_ partitions were correctly proven and move on without applying any penalties.

## Usage

* During large network updates that could potentially reduce chain quality (e.g., ones with time consuming state-upgrades), `MaintenenceWindow() bool` will return true starting at the upgrade epoch and ending some time after the upgrade epoch (likely 1 hour).
* In the case of a chain-halt and an emergency network upgrade:
    * The maintenance window would begin at the point where the network resumes.
    * The maintenance window would end some number of hours later when the chain is expected to be stable and caught up.

**Comment by jennijuju** [comment]
A fip is created https://github.com/filecoin-project/FIPs/pull/106

**Comment by Stebalien** [comment]
Note: These are related, but not quite the same. The goal here is to have a
way to simply pause fault marking for a period of time. That's fine for
a very short period (a day), less fine for a week or more.

**Comment by f8-ptrk** [comment]
> This is mitigated by the fact that no penalties are paid for missed Window PoSt. Unfortunately, power that wasn't proven is still lost until the next Window PoSt.

isn't that exactly how the network is intended to work?

**Comment by Stebalien** [comment]
>> This is mitigated by the fact that no penalties are paid for missed Window PoSt. Unfortunately, power that wasn't proven is still lost until the next Window PoSt.
>
> isn't that exactly how the network is intended to work? 

Normally, yes. This proposal exists for cases where proving power is
actually impossible or might be impossible for some reason (e.g., a
network outage, risky network upgrade, etc.). Maintenance windows would
never last more than a few hours at most.

First, large, sudden changes to power can impact chain quality. The
network should recover, but it could make recovery from network
outages slower.

Second, restoring power requires non-trivial state operations (at the
moment, at least). As storage capacity in the network grows, we could
get to a point where a network outage could cause more power to be lost
than can be restored in a single day (due to chain bandwidth
limitations). This would likely lead to lots of congestion and could
prolong network instability.

**Comment by kaitlin-beegle** [comment]
Closing, as this issue is currently being discussed in thread #103
