### ISSUE TITLE
Consider reverting FIP-0009

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/FIPs#86]
Optimistic WindowPoSt largely obviates the need for FIP-0009, so we can consider reverting it. We could also wait until FIP-0013 drives down costs even further.

**Comment by anorth** [comment]
Yes we should do this. The free Window PoSt distorts the gas market and removes any incentives for miners to reduce consumption of chain bandwidth by batching multiple partitions into each message.

**Comment by rjan90** [comment]
I definitely think it is a good idea to revert FIP-0009 after the `Network Hyperdrive` upgrade

**Comment by arajasek** [comment]
Since implemented in FIP-0015.
