### ISSUE TITLE
FIP Proposal: Pack arbitrary data in CC sectors

### ISSUE THREAD

**Issue by i-life-i** [filecoin-project/FIPs#89]
## Simple Summary

For CC sectors, allow miners to choose if they want to seal empty data or pack data pieces which could be real for CC
sector, and it can be verified accordingly.

## Abstract

Currently in seal process, miners pack empty pieces (all zeros) into CC sectors, after porep finished, create precommit
messages with empty dealID information. In verification of commit messages, verifier will get the DealID from
corresponding precommit info, and if DealID is empty, verifier recover the unsealed id by all zeros, which limit the CC
sector to seal only zeroed data.

## Change Motivation

We propose design to allow miners to pack real data for CC sectors, add unsealed id in precommit message and keep it on
chain. It introduce the possibility for CC upgrade without re-seal, and turn the piece into verified data afterwards (
Separated FIPs).

## Specification

1. CLI for associate sector ID with data files in local FS. (lotus change)
2. Add piece change for CC sector to read the mapping relationship between sector ID and data files and process
accordingly if there is any, if there is no mapping than keep the add piece process as is. (lotus change and
filecoin_ffi)
3. Add data field “unsealed ID” in precommit.info and populate value in it in . (lotus/spec actor change)
4. Add Optional data field “unsealed ID” in SectorOnChainInfo (for further CC upgrade verification between unsealed id
and piece CID)/SealVerifyStuff struct, (spec actor change)
5. In getVerifyInfo, if “unsealed ID” of SealVerifyStuff is not empty and dealIDs is empty, than use it for commD,
otherwise keep the logic as is (spec actor change)
6. In ConfirmSectorProofsValid, populate “unsealed ID” in the additional field of SectorOnChainInfo, this is for future
verification (spec actor change)

## Design Rationale

Extra onchain storage for “unsealed ID” in SectorOnChainInfo will be required. As this field provides the possibility
for post-verification between data pieces and unsealed ID.

## Backwards Compatibility

Fully backwards compatibility is expected

## Security Considerations

N/A

## Incentive Considerations

No impact on existing incentives, but provides extra flexibility to miners to pack real data in CC sectors. As the
onchain unsealed id is available, the cheaper CC upgrade and new process to assign DataCap is possible for the follow up
FIP

## Implementation

WIP

## Copyright

Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by magik6k** [comment]
This is basically the same as https://github.com/filecoin-project/FIPs/issues/57

**Comment by jennijuju** [comment]
@i-life-i As @magik6k suggested above, would you mind migrating your discussion to #57 unless you meant to submit a formal FIP, which in that case it should be a PR.

**Comment by jennijuju** [comment]
Duplicated with https://github.com/filecoin-project/FIPs/issues/57
