### ISSUE TITLE
FIP 0011 Bug

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/FIPs#90]
Persisting a slack conversation here

Hey @Kubuxu I think FIP0011 has a mistake.  It claims that current consensus fault penalty is `5 * BlockReward` [here](https://github.com/filecoin-project/FIPs/blob/6db88a7d5cdf26462f130b78d6e05b56e39442ad/FIPS/fip-0011.md#specification) but its actually just `BlockReward` from [here](https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/miner/monies.go#L186) as this function both multiplies by 5 and divides by 5.
If I understand the motivation behind FIP0011 I think this means the consensus fault reporting reward should become `BlockReward / 20`, the current max possible.  Let me know if you're in agreement on all this.  If so would you mind amending the FIP to fix this?

FYI @placer14 us resolving this blocks your implementation PR

**Comment by Kubuxu** [comment]
BR is a single block reward not a total epoch reward.

**Comment by Stebalien** [comment]
BR is usually the expected block reward for a sector over a 24hr period,
not the reward for a single block.

**Comment by ZenGround0** [comment]
Thanks @Kubuxu I was mistakenly thinking thisEpochRewardSmoothed was a single block's reward.
