### ISSUE TITLE
FIP 0075 contains an invalid `created` date in the frontmatter

### ISSUE THREAD

**Issue by timelytree** [filecoin-project/FIPs#969]
Just a heads up that the `created` date in the frontmatter of [FIP 0075](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0075.md) is set to `2023-28-28`, which is an invalid date (there is no month `28`). @jennijuju I think you may know what the correct date is here?

**Comment by rjan90** [comment]
It should be `2023-08-28` looking at the orginal PR date: https://github.com/filecoin-project/FIPs/pull/817. Want submit a PR fixing up the date?
